// io_defs_generated.h - AUTO-GENERATED from src/user/io_definitions.json
// Do not edit this file manually. Edit src/user/io_definitions.json instead,
// then run: python scripts/generate_io_header.py

#ifndef IO_DEFS_GENERATED_H
#define IO_DEFS_GENERATED_H

// --- Output definitions (IDO_*) ---
#define IDO_STARTLED       0
#define IDO_RSLING         1
#define IDO_LSLING         2
#define IDO_LFLIP          3
#define IDO_RFLIP          4
#define IDO_EJECT          5
#define IDO_NEOPIXEL0      6
#define IDO_LSLINGLED      7
#define IDO_RSLINGLED      8
#define IDO_LINLANELED     9
#define IDO_RINLANELED     10
#define IDO_SAVELED        11
#define IDO_POP1           12
#define IDO_POP2           13
#define IDO_POP3           14
#define IDO_INN1LED        15
#define IDO_INN2LED        16
#define IDO_INN3LED        17
#define IDO_KEY1LED        18
#define IDO_KEY2LED        19
#define IDO_KEY3LED        20
#define NUM_OUTPUTS        21

// --- Input definitions (IDI_*) ---
#define IDI_LFLIP          0
#define IDI_RFLIP          1
#define IDI_LACTIVATE      2
#define IDI_RACTIVATE      3
#define IDI_START          4
#define IDI_RESET          5
#define IDI_LINLANE        6
#define IDI_RINLANE        7
#define IDI_BALLDRAIN      8
#define IDI_BALLREADY      9
#define IDI_BALLDELIVERED  10
#define IDI_RSLING         11
#define IDI_LSLING         12
#define IDI_POP1           13
#define IDI_POP2           14
#define IDI_POP3           15
#define IDI_INN1           16
#define IDI_INN2           17
#define IDI_INN3           18
#define IDI_KEY1           19
#define IDI_KEY2           20
#define IDI_KEY3           21
#define NUM_INPUTS         22

#endif // IO_DEFS_GENERATED_H
