#!/usr/bin/env python3
"""Generate Graphviz state diagrams from the table-transition registries."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_DIR = ROOT / "documentation" / "state_map"
OUTPUT_DIR = REGISTRY_DIR / "generated_maps"

STYLE_BY_KIND = {
    "table-state": {"color": "#2563eb", "style": "solid"},
    "mode-entry": {"color": "#7c3aed", "style": "dashed"},
    "mode-exit": {"color": "#7c3aed", "style": "dashed"},
    "success": {"color": "#15803d", "style": "solid"},
    "failure": {"color": "#dc2626", "style": "solid"},
    "conditional": {"color": "#d97706", "style": "dotted"},
    "loop": {"color": "#64748b", "style": "solid"},
    "external": {"color": "#64748b", "style": "dashed"},
}


def dot_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def load_registry(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError(f"{path}: invalid JSON: {error}") from error

    required = {"title", "nodes", "transitions"}
    missing = required - data.keys()
    if missing:
        raise ValueError(f"{path}: missing required keys: {', '.join(sorted(missing))}")
    if not isinstance(data["nodes"], list) or not isinstance(data["transitions"], list):
        raise ValueError(f"{path}: nodes and transitions must be arrays")
    return data


def validate_registry(path: Path, data: dict[str, Any]) -> None:
    node_ids: set[str] = set()
    for node in data["nodes"]:
        if not isinstance(node, dict) or not all(key in node for key in ("id", "label", "group")):
            raise ValueError(f"{path}: every node requires id, label, and group")
        if node["id"] in node_ids:
            raise ValueError(f"{path}: duplicate node id {node['id']}")
        node_ids.add(node["id"])

    for index, transition in enumerate(data["transitions"], start=1):
        required = {"from", "to", "kind", "trigger", "source"}
        if not isinstance(transition, dict) or not required.issubset(transition):
            raise ValueError(f"{path}: transition {index} requires {', '.join(sorted(required))}")
        unknown = {transition["from"], transition["to"]} - node_ids
        if unknown:
            raise ValueError(f"{path}: transition {index} references unknown node(s): {', '.join(sorted(unknown))}")
        if transition["kind"] not in STYLE_BY_KIND:
            raise ValueError(f"{path}: transition {index} uses unknown kind {transition['kind']}")


def render_dot(data: dict[str, Any]) -> str:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for node in data["nodes"]:
        groups[node["group"]].append(node)

    lines = [
        "// Generated by scripts/generate_state_map.py. Do not edit manually.",
        "digraph StateMap {",
        "  graph [rankdir=LR, bgcolor=\"#ffffff\", fontname=\"Arial\", pad=0.35, nodesep=0.55, ranksep=0.9];",
        "  node [shape=box, style=\"rounded,filled\", fillcolor=\"#f8fafc\", color=\"#334155\", fontname=\"Arial\", margin=\"0.18,0.11\"];",
        "  edge [fontname=\"Arial\", fontsize=10, arrowsize=0.75];",
        f"  label={dot_quote(data['title'])};",
        "  labelloc=\"t\";",
        "  fontsize=20;",
        "  fontname=\"Arial Bold\";",
    ]

    for group_index, (group, nodes) in enumerate(groups.items()):
        lines.extend([
            f"  subgraph cluster_{group_index} {{",
            f"    label={dot_quote(group)};",
            "    color=\"#cbd5e1\";",
            "    style=\"rounded\";",
            "    penwidth=1.2;",
        ])
        for node in nodes:
            lines.append(f"    {dot_quote(node['id'])} [label={dot_quote(node['label'])}];")
        lines.append("  }")

    legend_rows = ["<TR><TD COLSPAN='4'><B>Legend</B></TD></TR>"]
    legend_items = list(STYLE_BY_KIND.items())
    for index in range(0, len(legend_items), 2):
        cells: list[str] = []
        for kind, style in legend_items[index:index + 2]:
            cells.extend([
                f"<TD BGCOLOR='{style['color']}' WIDTH='12'></TD>",
                f"<TD ALIGN='LEFT'>{kind}</TD>",
            ])
        while len(cells) < 4:
            cells.append("<TD></TD>")
        legend_rows.append("<TR>" + "".join(cells) + "</TR>")
    legend_label = "<" + "<TABLE BORDER='1' COLOR='#cbd5e1' CELLBORDER='0' CELLSPACING='0' CELLPADDING='4'>" + "".join(legend_rows) + "</TABLE>" + ">"
    lines.append(f"  legend [shape=plain, label={legend_label}];")

    for transition in data["transitions"]:
        style = STYLE_BY_KIND[transition["kind"]]
        label = f"{transition['trigger']}\\n[{transition['kind']}]"
        lines.append(
            f"  {dot_quote(transition['from'])} -> {dot_quote(transition['to'])} "
            f"[label={dot_quote(label)}, color={dot_quote(style['color'])}, "
            f"fontcolor={dot_quote(style['color'])}, style={dot_quote(style['style'])}];"
        )

    lines.append("}")
    return "\n".join(lines) + "\n"


def generate(registry_path: Path, render_svg: bool) -> tuple[Path, Path | None]:
    data = load_registry(registry_path)
    validate_registry(registry_path, data)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    generated_date = date.today().isoformat()
    output_dot = OUTPUT_DIR / f"{registry_path.stem}_{generated_date}.dot"
    output_dot.write_text(render_dot(data), encoding="utf-8")

    output_svg = OUTPUT_DIR / f"{registry_path.stem}_{generated_date}.svg"
    if render_svg:
        subprocess.run(["dot", "-Tsvg", str(output_dot), "-o", str(output_svg)], check=True)
        return output_dot, output_svg
    return output_dot, None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render-svg", action="store_true", help="Require Graphviz and render SVG files.")
    parser.add_argument("--check", action="store_true", help="Validate registries without writing outputs.")
    args = parser.parse_args()

    registry_paths = sorted(REGISTRY_DIR.glob("*_transitions.json"))
    registry_paths.insert(0, REGISTRY_DIR / "transitions.json")
    registry_paths = list(dict.fromkeys(path for path in registry_paths if path.exists()))
    if not registry_paths:
        print(f"No registries found in {REGISTRY_DIR}", file=sys.stderr)
        return 1

    try:
        for registry_path in registry_paths:
            data = load_registry(registry_path)
            validate_registry(registry_path, data)
            if args.check:
                print(f"Validated {registry_path.relative_to(ROOT)}")
                continue
            render_svg = args.render_svg or shutil.which("dot") is not None
            dot_path, svg_path = generate(registry_path, render_svg)
            print(f"Generated {dot_path.relative_to(ROOT)}")
            if svg_path:
                print(f"Generated {svg_path.relative_to(ROOT)}")
            elif args.render_svg:
                raise RuntimeError("Graphviz 'dot' was requested but is not available on PATH")
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        print(f"State map generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
