#!/usr/bin/env python3
"""
generate_io_header.py - Generate io_defs_generated.h from io_definitions.json

Reads the IO definitions JSON file and produces a C/C++ header file containing
#define constants for all input (IDI_*) and output (IDO_*) identifiers, plus
NUM_INPUTS and NUM_OUTPUTS counts.

Usage:
    python scripts/generate_io_header.py [json_path] [header_path]

Defaults:
    json_path   = io_definitions.json  (project root)
    header_path = src/io_defs_generated.h
"""

import json
import sys
import os

def main():
    # Determine paths (default to project-root-relative)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)

    json_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(project_root, "io_definitions.json")
    header_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(project_root, "src", "io_defs_generated.h")

    # Read JSON
    with open(json_path, "r") as f:
        data = json.load(f)

    outputs = data.get("outputs", [])
    inputs = data.get("inputs", [])

    # Validate: check for duplicate ids and indices
    seen_ids = set()
    seen_out_idx = set()
    seen_in_idx = set()

    for o in outputs:
        if o["id"] in seen_ids:
            print(f"ERROR: Duplicate id '{o['id']}' in outputs", file=sys.stderr)
            sys.exit(1)
        if o["idx"] in seen_out_idx:
            print(f"ERROR: Duplicate idx {o['idx']} in outputs (id: {o['id']})", file=sys.stderr)
            sys.exit(1)
        seen_ids.add(o["id"])
        seen_out_idx.add(o["idx"])

    for i in inputs:
        if i["id"] in seen_ids:
            print(f"ERROR: Duplicate id '{i['id']}' in inputs", file=sys.stderr)
            sys.exit(1)
        if i["idx"] in seen_in_idx:
            print(f"ERROR: Duplicate idx {i['idx']} in inputs (id: {i['id']})", file=sys.stderr)
            sys.exit(1)
        seen_ids.add(i["id"])
        seen_in_idx.add(i["idx"])

    # Compute NUM_OUTPUTS and NUM_INPUTS as max index + 1
    num_outputs = max(o["idx"] for o in outputs) + 1 if outputs else 0
    num_inputs = max(i["idx"] for i in inputs) + 1 if inputs else 0

    # Find the longest id name for alignment
    all_ids = [o["id"] for o in outputs] + [i["id"] for i in inputs] + ["NUM_OUTPUTS", "NUM_INPUTS"]
    max_id_len = max(len(name) for name in all_ids)

    # Generate header content
    lines = []
    lines.append("// io_defs_generated.h - AUTO-GENERATED from io_definitions.json")
    lines.append("// Do not edit this file manually. Edit io_definitions.json instead,")
    lines.append("// then run: python scripts/generate_io_header.py")
    lines.append("")
    lines.append("#ifndef IO_DEFS_GENERATED_H")
    lines.append("#define IO_DEFS_GENERATED_H")
    lines.append("")

    # Output defines
    lines.append("// --- Output definitions (IDO_*) ---")
    for o in sorted(outputs, key=lambda x: x["idx"]):
        padding = " " * (max_id_len - len(o["id"]))
        lines.append(f"#define {o['id']}{padding}  {o['idx']}")
    padding = " " * (max_id_len - len("NUM_OUTPUTS"))
    lines.append(f"#define NUM_OUTPUTS{padding}  {num_outputs}")
    lines.append("")

    # Input defines
    lines.append("// --- Input definitions (IDI_*) ---")
    for i in sorted(inputs, key=lambda x: x["idx"]):
        padding = " " * (max_id_len - len(i["id"]))
        lines.append(f"#define {i['id']}{padding}  {i['idx']}")
    padding = " " * (max_id_len - len("NUM_INPUTS"))
    lines.append(f"#define NUM_INPUTS{padding}  {num_inputs}")
    lines.append("")
    lines.append("#endif // IO_DEFS_GENERATED_H")
    lines.append("")

    new_content = "\n".join(lines)

    # Only write if content changed (avoid triggering unnecessary rebuilds)
    if os.path.exists(header_path):
        with open(header_path, "r") as f:
            existing = f.read()
        if existing == new_content:
            print(f"io_defs_generated.h is up to date (no changes)")
            return

    os.makedirs(os.path.dirname(header_path), exist_ok=True)
    with open(header_path, "w") as f:
        f.write(new_content)

    print(f"Generated {header_path} with {len(outputs)} outputs and {len(inputs)} inputs")


if __name__ == "__main__":
    main()
