// Pinball_Table_ModeInTower.cpp:  PBTBL_INTOWER mode implementation
//   Handles the tower lock screen. Entered when IDI_TOWER sensor is triggered.
//   Reuses the main screen base rendering (background, scores, status) and
//   renders tower-specific content only within the main status/scoring area.
//   No exit condition yet; will be added in a future task.

// Copyright (c) 2025 Jeffrey D. Bock, unless otherwise noted. Licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.
// The license can be found here: <https://creativecommons.org/licenses/by-nc/4.0/>.
// Additional details can also be found in the license file in the root of the project.

#include "Pinball_Engine.h"
#include "Pinball_Table.h"
#include "PBDevice.h"
#include <cmath>
#include <cstdlib>

namespace {
struct D20Vec3 {
    float x, y, z;
};

// Continuous spin speeds (degrees/second) while the die is rolling.
static constexpr float kD20SpinSpeedXDegPerSec = 1800.0f;
static constexpr float kD20SpinSpeedYDegPerSec = 2160.0f;
static constexpr float kD20SpinSpeedZDegPerSec = 2520.0f;

static inline float d20DegToRad(float deg) { return deg * 0.01745329252f; }
static inline float d20RadToDeg(float rad) { return rad * 57.29577951f; }

// Per-value face orientation table.  Indexed by (value - 1); each entry is the
// instance rotation (degrees, applied as PB3D's Ry*Rx*Rz) that lays the face
// bearing that number flat against the screen, upright.
//
// >>> These values are GENERATED by the D20 calibration tool: enable
// >>> D20_CALIBRATION in PBBuildSwitch.h, press IDI_START in the InTower
// >>> screen, align each face, then copy the logged tuples here. <<<
// Calibrated face orientations (from the in-table D20 calibration tool).
struct D20Orient { float rx, ry, rz; };
static const D20Orient kD20Orient[20] = {
    {  10.815763f, -179.906509f, -179.491333f }, // value 1
    {  35.677311f,  -11.936172f,   52.136024f }, // value 2
    { -58.095261f,  124.965378f,  -19.375134f }, // value 3
    {  44.081123f,  -74.950966f,   64.636345f }, // value 4
    { -58.883102f, -126.040024f,   20.600882f }, // value 5
    {  44.989437f,   74.649902f,  -65.023010f }, // value 6
    { -52.598091f,  179.344482f,    0.824432f }, // value 7
    {  35.892860f,   11.180718f,  -53.342773f }, // value 8
    { -40.396957f, -130.069214f,  142.760300f }, // value 9
    {  40.360752f,   49.940521f,   37.228291f }, // value 10
    { -39.587296f,  129.546478f, -141.962646f }, // value 11
    {  39.580391f,  -50.237770f,  -37.821663f }, // value 12
    { -35.687405f,  168.093658f,  127.864983f }, // value 13
    {  52.635639f,   -0.675681f,  179.159546f }, // value 14
    { -44.022305f,  105.121124f,  115.380226f }, // value 15
    {  58.088268f,  -54.941887f, -160.575974f }, // value 16
    { -44.944668f, -105.397247f, -114.978516f }, // value 17
    {  58.924267f,   54.068447f,  159.550232f }, // value 18
    { -35.882080f, -168.842484f, -126.649902f }, // value 19
    { -10.803362f,    0.105199f,   -0.510858f }  // value 20
};

// Global yaw trim added to every face's Y rotation so the displayed face reads
// perfectly flat (shared by the initial render and the roll snap).
static const float kD20YawTrimDeg = 10.0f;
}

// ========================================================================
// D20 CALIBRATION TOOL  ---  BEGIN
//   Self-contained, developer-only helper for generating kD20Orient[] above.
//   Gated entirely behind D20_CALIBRATION (see PBBuildSwitch.h).  To delete
//   the tool, remove this whole block plus the three small #ifdef D20_CALIBRATION
//   hooks in pbeUpdateStateInTower() / pbeRenderInTower() and the include below.
// ========================================================================
#ifdef D20_CALIBRATION
#include "3rdparty/cgltf.h"
#include <cstring>

namespace {

static constexpr int kD20CalibMaxFaces = 20;

struct D20CalibFace {
    D20Vec3 normal;       // model-space face normal (unit)
    D20Vec3 e1;           // in-plane basis vector 1
    D20Vec3 e2;           // in-plane basis vector 2 ( = normal x e1 )
};

static bool         s_d20CalibActive      = false; // calibration mode on/off
static bool         s_d20CalibParsed      = false; // model geometry parsed yet
static D20CalibFace s_d20CalibFaces[kD20CalibMaxFaces];
static int          s_d20CalibFaceCount   = 0;
static int          s_d20CalibPhase       = 0;     // 0 = orientation, 1 = number calibration
static float        s_d20CalibAngleOffset = 0.0f;  // hand-tuned in-plane rotation (rad)
static int          s_d20CalibFaceIdx     = 0;     // current face being aligned
static int          s_d20CalibCandIdx     = 0;     // which corner (0..2, 120deg apart)
static int          s_d20CalibValue       = 1;     // value assigned to this face

static inline D20Vec3 d20vSub(const D20Vec3& a, const D20Vec3& b)   { return { a.x - b.x, a.y - b.y, a.z - b.z }; }
static inline D20Vec3 d20vScale(const D20Vec3& a, float s)          { return { a.x * s, a.y * s, a.z * s }; }
static inline float   d20vDot(const D20Vec3& a, const D20Vec3& b)   { return a.x * b.x + a.y * b.y + a.z * b.z; }
static inline D20Vec3 d20vCross(const D20Vec3& a, const D20Vec3& b) { return { a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x }; }
static inline float   d20vLen(const D20Vec3& a)                     { return sqrtf(d20vDot(a, a)); }
static inline D20Vec3 d20vNorm(const D20Vec3& a)                    { float l = d20vLen(a); return (l > 1e-8f) ? d20vScale(a, 1.0f / l) : a; }

// Build the rotation that sends model-space normal n -> +Z (screen, toward the
// viewer) and the chosen up vector u -> +Y, then extract Euler angles matching
// PB3D's Ry*Rx*Rz application order.  Right vector r = u x n (right-handed).
static void d20CalibEuler(const D20Vec3& n, const D20Vec3& u,
                          float& rxDeg, float& ryDeg, float& rzDeg) {
    D20Vec3 nn = d20vNorm(n);
    D20Vec3 uu = d20vNorm(d20vSub(u, d20vScale(nn, d20vDot(u, nn)))); // orthogonalise up
    D20Vec3 rr = d20vNorm(d20vCross(uu, nn));

    // Rotation matrix rows are r, u, n.  For Ry*Rx*Rz:  R[1][2] = -sin(rx),
    // R[0][2]=sy*cx, R[2][2]=cy*cx, R[1][0]=cx*sz, R[1][1]=cx*cz.
    float rxr = asinf(fmaxf(-1.0f, fminf(1.0f, -uu.z)));
    float ryr, rzr;
    if (fabsf(cosf(rxr)) > 1e-4f) {
        ryr = atan2f(rr.z, nn.z);
        rzr = atan2f(uu.x, uu.y);
    } else {
        ryr = atan2f(-nn.x, rr.x);
        rzr = 0.0f;
    }
    rxDeg = d20RadToDeg(rxr);
    ryDeg = d20RadToDeg(ryr);
    rzDeg = d20RadToDeg(rzr);
}

// Parse d20dice.glb, cluster triangles into faces by normal, keep the 20
// largest-area clusters, and for each derive an in-plane basis plus the angle
// toward one triangle corner.  Returns true on success.
static bool d20CalibParseModel() {
    if (s_d20CalibParsed) return (s_d20CalibFaceCount > 0);
    s_d20CalibParsed = true;
    s_d20CalibFaceCount = 0;

    const char* path = "src/user/resources/3d/d20dice.glb";
    cgltf_options options;
    memset(&options, 0, sizeof(options));
    cgltf_data* data = nullptr;
    if (cgltf_parse_file(&options, path, &data) != cgltf_result_success) return (false);
    if (cgltf_load_buffers(&options, data, path) != cgltf_result_success) { cgltf_free(data); return (false); }

    // Cluster accumulators
    struct Cluster {
        D20Vec3 nSum;     // area-weighted normal sum
        D20Vec3 cSum;     // area-weighted centroid sum
        float   area;     // total area
    };
    static Cluster clusters[256];
    int clusterCount = 0;

    // First pass: accumulate clusters
    for (cgltf_size mi = 0; mi < data->meshes_count; ++mi) {
        cgltf_mesh* mesh = &data->meshes[mi];
        for (cgltf_size pi = 0; pi < mesh->primitives_count; ++pi) {
            cgltf_primitive* prim = &mesh->primitives[pi];
            if (prim->type != cgltf_primitive_type_triangles) continue;
            cgltf_accessor* posAcc = nullptr;
            for (cgltf_size ai = 0; ai < prim->attributes_count; ++ai) {
                if (prim->attributes[ai].type == cgltf_attribute_type_position) { posAcc = prim->attributes[ai].data; break; }
            }
            if (!posAcc) continue;
            cgltf_size triCount = prim->indices ? (prim->indices->count / 3) : (posAcc->count / 3);
            for (cgltf_size t = 0; t < triCount; ++t) {
                cgltf_size i0, i1, i2;
                if (prim->indices) {
                    i0 = cgltf_accessor_read_index(prim->indices, t * 3 + 0);
                    i1 = cgltf_accessor_read_index(prim->indices, t * 3 + 1);
                    i2 = cgltf_accessor_read_index(prim->indices, t * 3 + 2);
                } else { i0 = t * 3; i1 = t * 3 + 1; i2 = t * 3 + 2; }
                D20Vec3 v0, v1, v2;
                cgltf_accessor_read_float(posAcc, i0, &v0.x, 3);
                cgltf_accessor_read_float(posAcc, i1, &v1.x, 3);
                cgltf_accessor_read_float(posAcc, i2, &v2.x, 3);
                D20Vec3 cr = d20vCross(d20vSub(v1, v0), d20vSub(v2, v0));
                float area2 = d20vLen(cr);
                if (area2 < 1e-9f) continue;
                D20Vec3 nrm = d20vScale(cr, 1.0f / area2);
                D20Vec3 cen = d20vScale(D20Vec3{ v0.x + v1.x + v2.x, v0.y + v1.y + v2.y, v0.z + v1.z + v2.z }, 1.0f / 3.0f);
                float area = area2 * 0.5f;

                int found = -1;
                for (int c = 0; c < clusterCount; ++c) {
                    D20Vec3 cn = d20vNorm(clusters[c].nSum);
                    if (d20vDot(cn, nrm) > 0.95f) { found = c; break; }
                }
                if (found < 0 && clusterCount < 256) { found = clusterCount++; clusters[found] = { {0,0,0}, {0,0,0}, 0.0f }; }
                if (found >= 0) {
                    clusters[found].nSum   = D20Vec3{ clusters[found].nSum.x + nrm.x * area, clusters[found].nSum.y + nrm.y * area, clusters[found].nSum.z + nrm.z * area };
                    clusters[found].cSum   = D20Vec3{ clusters[found].cSum.x + cen.x * area, clusters[found].cSum.y + cen.y * area, clusters[found].cSum.z + cen.z * area };
                    clusters[found].area  += area;
                }
            }
        }
    }

    // Keep the 20 largest-area clusters
    int order[256];
    for (int i = 0; i < clusterCount; ++i) order[i] = i;
    for (int i = 0; i < clusterCount; ++i)
        for (int j = i + 1; j < clusterCount; ++j)
            if (clusters[order[j]].area > clusters[order[i]].area) { int tmp = order[i]; order[i] = order[j]; order[j] = tmp; }
    int keep = clusterCount < kD20CalibMaxFaces ? clusterCount : kD20CalibMaxFaces;

    for (int k = 0; k < keep; ++k) {
        D20Vec3 n = d20vNorm(clusters[order[k]].nSum);
        // Build an arbitrary in-plane basis.  The exact in-plane rotation that
        // makes the bottom edge horizontal is dialed in by hand in the
        // orientation phase (s_d20CalibAngleOffset), not estimated from geometry.
        D20Vec3 ref = (fabsf(n.y) < 0.9f) ? D20Vec3{ 0, 1, 0 } : D20Vec3{ 1, 0, 0 };
        D20Vec3 e1 = d20vNorm(d20vCross(n, ref));
        D20Vec3 e2 = d20vNorm(d20vCross(n, e1));
        s_d20CalibFaces[k].normal = n;
        s_d20CalibFaces[k].e1 = e1;
        s_d20CalibFaces[k].e2 = e2;
    }
    s_d20CalibFaceCount = keep;

    cgltf_free(data);
    return (s_d20CalibFaceCount > 0);
}

// Current candidate orientation for the face/corner the user is inspecting.
static void d20CalibCurrentOrient(float& rxDeg, float& ryDeg, float& rzDeg) {
    if (s_d20CalibFaceCount <= 0) { rxDeg = ryDeg = rzDeg = 0.0f; return; }
    const D20CalibFace& f = s_d20CalibFaces[s_d20CalibFaceIdx % s_d20CalibFaceCount];
    float ang = s_d20CalibAngleOffset + (float)s_d20CalibCandIdx * 1.04719755f; // hand-tuned offset + 60 deg steps
    D20Vec3 up = { f.e1.x * cosf(ang) + f.e2.x * sinf(ang),
                   f.e1.y * cosf(ang) + f.e2.y * sinf(ang),
                   f.e1.z * cosf(ang) + f.e2.z * sinf(ang) };
    d20CalibEuler(f.normal, up, rxDeg, ryDeg, rzDeg);
}

}
#endif // D20_CALIBRATION
// ========================================================================
// D20 CALIBRATION TOOL  ---  END
// ========================================================================

// ========================================================================
// PBTBL_INTOWER: Load Function
// ========================================================================

bool PBEngine::pbeLoadInTower() {

    if (m_inTowerLoaded) return (true);

    // InTower reuses the main screen background resources; ensure they are loaded
    if (!pbeLoadMainScreen()) return (false);

    m_TowerClimbId = gfxLoadSprite("TowerClimb", "src/user/resources/textures/towerclimb.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerClimbId, 80, 80, 160, 255);

    // Load dungeon door grid sprites
    m_DoorOpenId = gfxLoadSprite("DoorOpen", "src/user/resources/textures/dooropen.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorOpenId, 255, 255, 255, 255);

    m_DoorClosedId = gfxLoadSprite("DoorClosed", "src/user/resources/textures/doorclosed.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorClosedId, 255, 255, 255, 255);

    m_DoorBlockedId = gfxLoadSprite("DoorBlocked", "src/user/resources/textures/doorblocked.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorBlockedId, 255, 255, 255, 255);

    m_DoorWall1Id = gfxLoadSprite("DoorWall1", "src/user/resources/textures/doorwall1.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorWall1Id, 255, 255, 255, 255);

    m_DoorWall2Id = gfxLoadSprite("DoorWall2", "src/user/resources/textures/doorwall2.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorWall2Id, 255, 255, 255, 255);

    m_DoorStairsId = gfxLoadSprite("DoorStairs", "src/user/resources/textures/doorstairs.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorStairsId, 255, 255, 255, 255);

    if (m_DoorOpenId == NOSPRITE || m_DoorClosedId == NOSPRITE || m_DoorBlockedId == NOSPRITE ||
        m_DoorWall1Id == NOSPRITE || m_DoorWall2Id == NOSPRITE || m_DoorStairsId == NOSPRITE) {
        pbeSendConsole("ERROR: Failed to load InTower door sprites");
        return (false);
    }

    // Load the InTower d20 model once and keep a persistent instance.
    if (!m_inTowerD20Loaded) {
        m_inTowerD20ModelId = pb3dLoadModel("src/user/resources/3d/d20dice.glb");
        if (m_inTowerD20ModelId == 0) {
            pbeSendConsole("WARNING: Failed to load d20dice.glb");
        } else {
            m_inTowerD20InstanceId = pb3dCreateInstance(m_inTowerD20ModelId);
            pb3dSetInstanceScale(m_inTowerD20InstanceId, 0.63f);
            pb3dSetInstanceVisible(m_inTowerD20InstanceId, true);
            m_inTowerD20Value = 1;
            m_inTowerD20RollState = 0;
            // Show value 1 face-up using its calibrated tuple (+ global yaw trim).
            m_inTowerD20RotX = kD20Orient[0].rx;
            m_inTowerD20RotY = kD20Orient[0].ry + kD20YawTrimDeg;
            m_inTowerD20RotZ = kD20Orient[0].rz;
            pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
            m_inTowerD20Loaded = true;
        }
    }

    m_inTowerLoaded = true;
    return (true);
}

// ========================================================================
// PBTBL_INTOWER: Dungeon Grid Initialization
// ========================================================================

// File-scope test variable: tracks which dungeon level is displayed in InTower
// (for testing only; not tied to player-state dungeonLevel)
static int s_testDungeonLevel = 1;

// Initialize the dungeon grid for a given player at the specified level.
//   playerNum : 0-3 (clamped)
//   level     : 1=linear 3-floor (col 1 only)
//               2=4-floor 2-col (cols 1-2, random ladders)
//               3=5-floor 3-col (cols 0-2, random ladders)
void PBEngine::pbeInitDungeonGrid(int playerNum, int level) {

    // Clamp inputs to valid ranges
    if (playerNum < 0) playerNum = 0;
    if (playerNum > 3) playerNum = 3;
    if (level < 1) level = 1;
    if (level > 3) level = 3;

    TowerDungeonGrid& grid = m_playerStates[playerNum].dungeonGrid;

    // Clear all cells to DOOR_NONE
    grid = TowerDungeonGrid();

    if (level == 1) {
        // ----------------------------------------------------------------
        // Level 1: linear 3-floor path, centre column only, no randomness
        // ----------------------------------------------------------------
        const int col = 1;
        const int numRows = 3;
        for (int r = 0; r < numRows; r++) {
            grid.cells[r][col].state = DoorState::DOOR_CLOSED;
        }
        // Ladders on floors 0 and 1; dragon lair on floor 2
        grid.cells[0][col].hasLadder   = true;
        grid.cells[1][col].hasLadder   = true;
        grid.cells[2][col].isDragonLair = true;

        // TODO: Initialize room metadata here (monsters, room type, etc.)

    } else if (level == 2) {
        // ----------------------------------------------------------------
        // Level 2: 4-floor path, cols 1-2, random ladder per row
        // ----------------------------------------------------------------
        const int activeCols[2] = { 1, 2 };
        const int numActiveCols  = 2;
        const int numRows        = 4;

        for (int r = 0; r < numRows; r++) {
            for (int c = 0; c < numActiveCols; c++) {
                grid.cells[r][activeCols[c]].state = DoorState::DOOR_CLOSED;
            }
        }
        // One random ladder per non-top row
        for (int r = 0; r < numRows - 1; r++) {
            int pick = rand() % numActiveCols;
            grid.cells[r][activeCols[pick]].hasLadder = true;
        }
        // One random dragon lair on top row
        {
            int pick = rand() % numActiveCols;
            grid.cells[numRows - 1][activeCols[pick]].isDragonLair = true;
        }

        // TODO: Initialize room metadata here (monsters, room type, etc.)

    } else {
        // ----------------------------------------------------------------
        // Level 3: 5-floor path, all 3 cols (0-2), random ladder per row
        // ----------------------------------------------------------------
        const int activeCols[3] = { 0, 1, 2 };
        const int numActiveCols  = 3;
        const int numRows        = 5;

        for (int r = 0; r < numRows; r++) {
            for (int c = 0; c < numActiveCols; c++) {
                grid.cells[r][activeCols[c]].state = DoorState::DOOR_CLOSED;
            }
        }
        // One random ladder per non-top row
        for (int r = 0; r < numRows - 1; r++) {
            int pick = rand() % numActiveCols;
            grid.cells[r][activeCols[pick]].hasLadder = true;
        }
        // One random dragon lair on top row
        {
            int pick = rand() % numActiveCols;
            grid.cells[numRows - 1][activeCols[pick]].isDragonLair = true;
        }

        // TODO: Initialize room metadata here (monsters, room type, etc.)
    }

    // Randomize hasTorch for every active cell (determines doorwall1 vs doorwall2
    // on the wall to the right of that door).  Far-right column cells are also
    // randomized even though their wall is never rendered.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                grid.cells[r][c].hasTorch = (rand() % 2 == 1);
            }
        }
    }

    // Signal the render function to restart the zoom-in animation
    m_dungeonGridAnimPending = true;

    // Return the dungeon to fullscreen presentation phase
    m_inTowerDungeonPhase = 0;
    m_inTowerDoorJustOpened = false;
}

// ========================================================================
// PBTBL_INTOWER: Dungeon Grid Render
// ========================================================================

// Render the dungeon door grid for the current player.
//   scale   : final/target scale factor (1.0 = native image size)
//   centerX : screen X of the grid centre
//   centerY : screen Y of the grid centre
//   animate : if true, zoom from 0 to scale over 2 s; reset triggered by
//             pbeInitDungeonGrid setting m_dungeonGridAnimPending
void PBEngine::pbeRenderDungeonGrid(float scale, int centerX, int centerY,
                                    bool animate,
                                    unsigned long currentTick, unsigned long /*lastTick*/) {

    TowerDungeonGrid& grid = m_playerStates[m_currentPlayer].dungeonGrid;

    // ---- Animated scale ------------------------------------------------
    // When animate=true, pbeInitDungeonGrid sets m_dungeonGridAnimPending.
    // The first render call after that latches the start tick and the grid
    // zooms from scale=0 to the target scale over 2000 ms.
    float renderScale = scale;
    if (animate) {
        if (m_dungeonGridAnimPending) {
            m_dungeonGridAnimStartTick = currentTick;
            m_dungeonGridAnimPending   = false;
        }
        float t = (currentTick >= m_dungeonGridAnimStartTick)
                  ? (float)(currentTick - m_dungeonGridAnimStartTick) / 1000.0f
                  : 0.0f;
        if (t > 1.0f) t = 1.0f;

        // Ease-out quadratic: scale grows fast early so the grid is nearly
        // full-size well before it arrives — only a small pop at the end.
        float tScale    = 1.0f - (1.0f - t) * (1.0f - t);
        renderScale     = scale * tScale;

        // Swirl path: begins at the bottom-centre door position and spirals
        // CCW into the final centre over 1 second.
        //   bottomOffset = distance from grid centre to row-0 (bottom door)
        //   using final scale so the start lines up with the door's real position.
        float finalDoorH   = (float)gfxGetBaseHeight(m_DoorOpenId) * scale;
        float finalRowStep = finalDoorH * 1.25f;          // doorH + doorH/4
        float bottomOffset = 2.0f * finalRowStep;         // 2 rows below centre

        float offsetMag = (1.0f - t) * bottomOffset;
        // CCW revolution: PI/2 (below) -> PI/2 + 2PI
        float angle = 1.5707963f + t * 6.2831853f;
        float rawX  = cosf(angle) * offsetMag * 0.4f;    // Narrow left swing to ~40% of orbit radius
        float rawY  = sinf(angle) * offsetMag;

        // Never shift right of the final position — keeps the grid inside the tower image
        float startShiftX = (1.0f - t) * 210.0f;  // +210 px right at t=0, fades to 0 at t=1
        float startShiftY = (1.0f - t) * -80.0f;  // -80 px up   at t=0, fades to 0 at t=1
        centerX += (int)(rawX < 0.0f ? rawX : 0.0f) + (int)startShiftX;
        centerY += (int)rawY + (int)startShiftY;
    }

    // ---- Layout metrics (all use renderScale for consistent zoom) -------
    int doorW  = (int)(gfxGetBaseWidth(m_DoorOpenId)  * renderScale);
    int doorH  = (int)(gfxGetBaseHeight(m_DoorOpenId) * renderScale);

    int gapH    = (int)((doorH / 4 + 10) * 0.5625f);
    int rowStep = doorH + gapH;

    int wallNativeW  = (int)gfxGetBaseWidth(m_DoorWall1Id);
    int colGap       = (int)(wallNativeW * renderScale / 4.0f);
    int colStep      = doorW + colGap;

    // ---- Row positions (centred at centerY) ----------------------------
    int rowPositions[5];
    int gridTop = centerY - (2 * rowStep);
    for (int r = 0; r < 5; r++) {
        rowPositions[r] = gridTop + (4 - r) * rowStep;
    }

    // ---- Column positions (smart centering for even / odd active cols) --
    // Scan active column range so the grid is always centred at centerX
    // regardless of whether an even or odd number of columns are in use.
    //   Odd  (1 or 3 cols): centre lands on the middle column.
    //   Even (2 cols)     : centre sits in the gap between the two columns.
    int minActiveCol = 3, maxActiveCol = -1;
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                if (c < minActiveCol) minActiveCol = c;
                if (c > maxActiveCol) maxActiveCol = c;
            }
        }
    }
    if (maxActiveCol < 0) { minActiveCol = 1; maxActiveCol = 1; }
    float centerColIdx = (minActiveCol + maxActiveCol) / 2.0f;

    int colPositions[3];
    for (int c = 0; c < 3; c++) {
        colPositions[c] = centerX + (int)((c - centerColIdx) * colStep);
    }

    // ---- Pass 1: Walls (lowest layer) ----------------------------------
    // Render wall horizontally between adjacent door columns on the same row.
    // Use doorwall1 (torch) if the left door has hasTorch set, else doorwall2.
    // Shifted 5 pixels left from the exact midpoint.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 2; c++) {
            if (grid.cells[r][c].state     != DoorState::DOOR_NONE &&
                grid.cells[r][c + 1].state != DoorState::DOOR_NONE) {
                int wallX = (colPositions[c] + colPositions[c + 1]) / 2 - 5;
                unsigned int wallSprite = grid.cells[r][c].hasTorch ? m_DoorWall1Id : m_DoorWall2Id;
                gfxRenderSprite(wallSprite, wallX, rowPositions[r], renderScale, 0.0f);
            }
        }
    }

    // ---- Pass 2: Blocked/Stairs overlays --------------------------------
    // For open doors, render doorstairs.png (shifted +6 px right) if the cell
    // has a ladder; otherwise render doorblocked.png at the original position.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state == DoorState::DOOR_OPEN) {
                if (grid.cells[r][c].hasLadder) {
                    gfxRenderSprite(m_DoorStairsId,
                                    colPositions[c] + 6,
                                    rowPositions[r],
                                    renderScale * 0.8f, 0.0f);
                } else {
                    gfxRenderSprite(m_DoorBlockedId,
                                    colPositions[c],
                                    rowPositions[r],
                                    renderScale * 0.8f, 0.0f);
                }
            }
        }
    }

    // ---- Pass 3: Doors (top layer) -------------------------------------
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state == DoorState::DOOR_NONE) continue;
            unsigned int spriteId = (grid.cells[r][c].state == DoorState::DOOR_OPEN)
                                    ? m_DoorOpenId : m_DoorClosedId;
            gfxRenderSprite(spriteId, colPositions[c], rowPositions[r], renderScale, 0.0f);
        }
    }
}

void PBEngine::pbeUpdateInTowerD20(unsigned long currentTick) {
    if (!m_inTowerD20Loaded) return;

#ifdef D20_CALIBRATION
    if (s_d20CalibActive) {
        // Calibration owns the orientation while active.
        float rx, ry, rz;
        d20CalibCurrentOrient(rx, ry, rz);
        pb3dSetInstanceRotation(m_inTowerD20InstanceId, rx, ry, rz);
        return;
    }
#endif

    if (m_inTowerD20RollState == 1) {
        // Spinning: advance all three axes continuously until the player stops it.
        float t = (currentTick >= m_inTowerD20SpinStartTick)
                ? (float)(currentTick - m_inTowerD20SpinStartTick) / 1000.0f : 0.0f;
        m_inTowerD20RotX = m_inTowerD20SpinBaseRotX + (kD20SpinSpeedXDegPerSec * t);
        m_inTowerD20RotY = m_inTowerD20SpinBaseRotY + (kD20SpinSpeedYDegPerSec * t);
        m_inTowerD20RotZ = m_inTowerD20SpinBaseRotZ + (kD20SpinSpeedZDegPerSec * t);
    }
    // RollState 0 (idle) and 2 (stopped) keep their current rotation; the stop
    // transition snaps to kD20Orient[value-1] in pbeUpdateStateInTower().

    pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
}

// ========================================================================
// PBTBL_INTOWER: Render Function
// ========================================================================

bool PBEngine::pbeRenderInTower(unsigned long currentTick, unsigned long lastTick) {

    if (!pbeLoadInTower()) {
        pbeSendConsole("ERROR: Failed to load InTower screen resources");
        return (false);
    }

    // Render the standard main screen base: black background, player scores,
    // status text and icons, NeoPixel animation
    if (!pbeRenderMainScreenBase(currentTick, lastTick)) {
        return (false);
    }

    // Render towerclimb image centered in the main score area
    int towerCenterX = ACTIVEDISPX + (1024 / 3);
    int towerCenterY = ACTIVEDISPY + 350;
    gfxRenderSprite(m_TowerClimbId, towerCenterX, towerCenterY);

    int towerHalfWidth  = (int)(gfxGetBaseWidth(m_TowerClimbId) / 2);
    int towerHalfHeight = (int)(gfxGetBaseHeight(m_TowerClimbId) / 2);
    int towerTopLeftX   = towerCenterX - towerHalfWidth;
    int towerTopLeftY   = towerCenterY - towerHalfHeight;

#ifdef D20_CALIBRATION
    // --- D20 CALIBRATION render override (developer tool) ----------------
    if (s_d20CalibActive && m_inTowerD20Loaded) {
        pbeUpdateInTowerD20(currentTick); // applies the current calib orientation
        pb3dSetInstancePositionPx(m_inTowerD20InstanceId, (float)towerCenterX, (float)towerCenterY - 40.0f, 0.0f);
        pb3dBegin();
        pb3dRenderInstance(m_inTowerD20InstanceId);
        pb3dEnd();

        float rx, ry, rz;
        d20CalibCurrentOrient(rx, ry, rz);

        // Render the D20 result, then the calibration detail below it, using the
        // same shadow-string renderer as the normal dice value (no snprintf).
        std::string angleText  = "rx " + std::to_string((int)lroundf(rx))
                               + "  ry " + std::to_string((int)lroundf(ry))
                               + "  rz " + std::to_string((int)lroundf(rz));
        std::string resultText;
        std::string faceText;
        std::string helpText;
        if (s_d20CalibPhase == 0) {
            resultText = "ORIENT: bottom edge horizontal";
            faceText   = "offset " + std::to_string((int)lroundf(d20RadToDeg(s_d20CalibAngleOffset))) + " deg";
            helpText   = "LFLIP/RFLIP=rotate  LACT/RACT=set  START=exit";
        } else {
            resultText = "D20: " + std::to_string(s_d20CalibValue);
            faceText   = "face " + std::to_string(s_d20CalibFaceIdx + 1) + "/" + std::to_string(s_d20CalibFaceCount)
                       + "  rot " + std::to_string(s_d20CalibCandIdx * 60) + " deg";
            helpText   = "LFLIP=face RFLIP=corner LACT/RACT=value(logs) START=exit";
        }

        // Render the calibration text at half the font's normal size (keep the
        // same vertical offsets so the lines do not overlap), then restore.
        float prevFontScale = gfxGetScaleFactor(m_StartMenuFontId);
        gfxSetScaleFactor(m_StartMenuFontId, prevFontScale * 0.5f, false);

        gfxRenderShadowString(m_StartMenuFontId, resultText, towerCenterX, towerCenterY + 80,  3, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, faceText,   towerCenterX, towerCenterY + 120, 2, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, angleText,  towerCenterX, towerCenterY + 145, 2, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, helpText,   towerCenterX, towerCenterY + 170, 1, GFX_TEXTCENTER, 0, 0, 0, 255, 2);

        gfxSetScaleFactor(m_StartMenuFontId, prevFontScale, false);

        gfxRenderSprite(m_PBTBLMainScreenBGId, ACTIVEDISPX, ACTIVEDISPY);
        pbeRenderStatusText(currentTick, lastTick);
        return (true);
    }
#endif

    static constexpr float kDungeonFullscreenScale  = 0.8625f; // 0.75 * 1.15
    static constexpr float kDungeonSmallScale       = 0.406f; // 0.325 * 1.25 — 25% bigger
    static constexpr float kDungeonTransitionDurMs  = 500.0f;  // shrink and grow duration

    // Anchor points: fullscreen centred on towerclimb (shifted up 50 px); small in right half
    int fullX  = towerCenterX;
    int fullY  = towerCenterY - 30;
    int smallX = towerCenterX + towerHalfWidth / 2 + 30;
    int smallY = towerCenterY;

    if (m_inTowerDungeonPhase == 0) {
        // ---- Phase 0: dungeon fills the intower area; dice hidden -------
        pbeRenderDungeonGrid(kDungeonFullscreenScale, fullX, fullY, true, currentTick, lastTick);
    }
    else if (m_inTowerDungeonPhase == 1) {
        // ---- Phase 1: shrink from fullscreen to small -------------------
        float elapsedMs = (currentTick >= m_inTowerShrinkAnimStartTick)
                          ? (float)(currentTick - m_inTowerShrinkAnimStartTick) : 0.0f;
        float t = elapsedMs / kDungeonTransitionDurMs;
        if (t >= 1.0f) {
            t = 1.0f;
            m_inTowerDungeonPhase = 2;  // Animation complete — show dice
        }
        // Smooth-step ease: t^2*(3-2t)
        float tEase       = t * t * (3.0f - 2.0f * t);
        float renderScale = kDungeonFullscreenScale + (kDungeonSmallScale - kDungeonFullscreenScale) * tEase;
        int   renderX     = fullX + (int)((smallX - fullX) * tEase);
        int   renderY     = fullY + (int)((smallY - fullY) * tEase);
        pbeRenderDungeonGrid(renderScale, renderX, renderY, false, currentTick, lastTick);
    }
    else if (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3) {
        // ---- Phase 2/3: dungeon at small position; dice visible ----------
        pbeRenderDungeonGrid(kDungeonSmallScale, smallX, smallY, false, currentTick, lastTick);

        if (m_inTowerD20Loaded) {
            pbeUpdateInTowerD20(currentTick);
            int diceX = towerTopLeftX + 220;
            int diceY = towerTopLeftY + 140;

            // While the die spins it hops around a small circle, then settles
            // back to the centre (its final resting spot) once it stops.
            float bounceX = 0.0f, bounceY = 0.0f;
            if (m_inTowerD20RollState == 1 || m_inTowerD20RollState == 2) {
                const float kBounceRadiusPx = 22.0f; // circle radius
                const float kBounceOmega    = 9.0f;  // rad/sec around the circle
                const float kBounceHopPx    = 10.0f; // extra vertical hop
                const float kSettleMs       = 350.0f;
                float spinSec = (currentTick >= m_inTowerD20SpinStartTick)
                              ? (float)(currentTick - m_inTowerD20SpinStartTick) / 1000.0f : 0.0f;
                float radius = kBounceRadiusPx;
                if (m_inTowerD20RollState == 2) {
                    // Ease the radius down to zero so it glides back to centre.
                    float s = (currentTick >= m_inTowerD20StopTick)
                            ? (float)(currentTick - m_inTowerD20StopTick) / kSettleMs : 0.0f;
                    if (s > 1.0f) s = 1.0f;
                    float ease = 1.0f - (1.0f - s) * (1.0f - s); // ease-out
                    radius = kBounceRadiusPx * (1.0f - ease);
                }
                float theta = spinSec * kBounceOmega;
                float scale = radius / kBounceRadiusPx;
                bounceX = radius * cosf(theta);
                bounceY = radius * sinf(theta) - fabsf(sinf(theta * 2.0f)) * kBounceHopPx * scale;
            }
            pb3dSetInstancePositionPx(m_inTowerD20InstanceId, (float)diceX + bounceX, (float)diceY + bounceY, 0.0f);
            pb3dBegin();
            pb3dRenderInstance(m_inTowerD20InstanceId);
            pb3dEnd();
            // m_inTowerD20Value holds the rolled value for later use (not shown).
        }
    }
    else {
        // ---- Phase 4: grow from small back to fullscreen; dice hidden ----
        float elapsedMs = (currentTick >= m_inTowerShrinkAnimStartTick)
                          ? (float)(currentTick - m_inTowerShrinkAnimStartTick) : 0.0f;
        float t = elapsedMs / kDungeonTransitionDurMs;
        if (t >= 1.0f) {
            t = 1.0f;
            m_inTowerDungeonPhase = 0;  // Animation complete — back to fullscreen
        }
        // Smooth-step ease: t^2*(3-2t)
        float tEase       = t * t * (3.0f - 2.0f * t);
        float renderScale = kDungeonSmallScale + (kDungeonFullscreenScale - kDungeonSmallScale) * tEase;
        int   renderX     = smallX + (int)((fullX - smallX) * tEase);
        int   renderY     = smallY + (int)((fullY - smallY) * tEase);
        pbeRenderDungeonGrid(renderScale, renderX, renderY, false, currentTick, lastTick);
    }

    // Render divider bars on top, same as pbeRenderMainScreen
    gfxRenderSprite(m_PBTBLMainScreenBGId, ACTIVEDISPX, ACTIVEDISPY);

    // Re-render ball text and status text above the tower image and overlay
    pbeRenderStatusText(currentTick, lastTick);

    return (true);
}

// ========================================================================
// PBTBL_INTOWER: State Update Function
// ========================================================================

void PBEngine::pbeUpdateStateInTower(stInputMessage inputMessage) {

    if (inputMessage.inputMsg == PB_IMSG_BUTTON && inputMessage.inputState == PB_ON) {

#ifdef D20_CALIBRATION
        // ------------------------------------------------------------
        // D20 CALIBRATION input handling (developer tool).  IDI_START
        // toggles the mode; while active, all input drives calibration and
        // normal InTower handling is bypassed.  Safe to remove this block.
        // ------------------------------------------------------------
        if (inputMessage.inputId == IDI_START) {
            s_d20CalibActive = !s_d20CalibActive;
            if (s_d20CalibActive) {
                if (!d20CalibParseModel()) {
                    pbeSendConsole("D20 CALIB: failed to parse d20dice.glb");
                    s_d20CalibActive = false;
                } else {
                    s_d20CalibPhase       = 0;   // start in the orientation phase
                    s_d20CalibAngleOffset = d20DegToRad(-90.0f);
                    s_d20CalibFaceIdx     = 0;
                    s_d20CalibCandIdx     = 0;
                    s_d20CalibValue       = 1;
                    pbeSendConsole("D20 CALIB: enabled - orient bottom edge horizontal (LFLIP/RFLIP), LACT/RACT to set");
                }
            } else {
                pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
                pbeSendConsole("D20 CALIB: disabled");
            }
            return;
        }
        if (s_d20CalibActive) {
            if (s_d20CalibPhase == 0) {
                // --- Phase 0: dial the in-plane rotation until the bottom edge
                // is horizontal.  Flippers nudge +/- 0.5 deg; activate locks it. ---
                const float kStep = d20DegToRad(0.5f);
                if (inputMessage.inputId == IDI_LFLIP) {
                    s_d20CalibAngleOffset -= kStep;
                } else if (inputMessage.inputId == IDI_RFLIP) {
                    s_d20CalibAngleOffset += kStep;
                } else if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                    s_d20CalibPhase = 1; // lock orientation, move on to number calibration
                    pbeSendConsole("D20 CALIB: orientation set - now stepping numbers (LACT/RACT logs each)");
                }
                return;
            }
            // --- Phase 1: number calibration (uses the locked orientation) ---
            if (inputMessage.inputId == IDI_LFLIP) {
                if (s_d20CalibFaceCount > 0) s_d20CalibFaceIdx = (s_d20CalibFaceIdx + 1) % s_d20CalibFaceCount;
                s_d20CalibCandIdx = 0;
            } else if (inputMessage.inputId == IDI_RFLIP) {
                s_d20CalibCandIdx = (s_d20CalibCandIdx + 1) % 6; // 60 deg steps
            } else if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                // Moving the value logs the tuple for the value currently shown
                // (the "previous" value) before advancing to the next one.
                float rx, ry, rz;
                d20CalibCurrentOrient(rx, ry, rz);
                std::string tuple = "{ " + std::to_string(rx) + "f, " + std::to_string(ry) + "f, "
                                  + std::to_string(rz) + "f }, // value " + std::to_string(s_d20CalibValue);
                pbeSendConsole(tuple);

                if (inputMessage.inputId == IDI_LACTIVATE) {
                    s_d20CalibValue = (s_d20CalibValue <= 1) ? 20 : s_d20CalibValue - 1;
                } else {
                    s_d20CalibValue = (s_d20CalibValue >= 20) ? 1 : s_d20CalibValue + 1;
                }
            }
            return;
        }
#endif // D20_CALIBRATION

        // ------------------------------------------------------------
        // Flippers: behaviour depends on current dungeon phase
        // ------------------------------------------------------------
        if (inputMessage.inputId == IDI_LFLIP || inputMessage.inputId == IDI_RFLIP) {

            if (m_inTowerDungeonPhase == 0) {
                if (!m_inTowerDoorJustOpened) {
                    // First press: open the next available door; stay fullscreen
                    TowerDungeonGrid& grid = m_playerStates[m_currentPlayer].dungeonGrid;
                    for (int r = 0; r < 5; r++) {
                        for (int c = 0; c < 3; c++) {
                            if (grid.cells[r][c].state != DoorState::DOOR_NONE &&
                                grid.cells[r][c].state != DoorState::DOOR_OPEN) {
                                grid.cells[r][c].state = DoorState::DOOR_OPEN;
                                m_inTowerDoorJustOpened = true;
                                goto doorOpenDone;
                            }
                        }
                    }
                    doorOpenDone:;
                } else {
                    // Second press: start shrink animation
                    m_inTowerDoorJustOpened = false;
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase = 1;
                }
            }
            else if (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3) {
                // Dice screen: flippers drive the roll state machine.
                //   state 0 (READY)    -> pick value now, start fast spin
                //   state 1 (SPINNING) -> stop spin, snap rolled value flat/upright
                //   state 2 (STOPPED)  -> grow dungeon back to fullscreen
                if (!m_inTowerD20Loaded) {
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase = 4;
                }
                else if (m_inTowerD20RollState == 0) {
                    m_inTowerD20Value         = (rand() % 20) + 1;
                    m_inTowerD20RollState     = 1;
                    m_inTowerD20SpinStartTick = GetTickCountGfx();
                    m_inTowerD20SpinBaseRotX  = m_inTowerD20RotX;
                    m_inTowerD20SpinBaseRotY  = m_inTowerD20RotY;
                    m_inTowerD20SpinBaseRotZ  = m_inTowerD20RotZ;
                    m_inTowerDungeonPhase     = 2;
                }
                else if (m_inTowerD20RollState == 1) {
                    // Global yaw trim: nudge every face slightly about Y so
                    // the displayed face reads perfectly flat.
                    const D20Orient& o = kD20Orient[(m_inTowerD20Value - 1) % 20];
                    m_inTowerD20RotX      = o.rx;
                    m_inTowerD20RotY      = o.ry + kD20YawTrimDeg;
                    m_inTowerD20RotZ      = o.rz;
                    m_inTowerD20RollState = 2;
                    m_inTowerD20StopTick  = GetTickCountGfx(); // begin bounce settle
                }
                else {
                    m_inTowerD20RollState        = 0;
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase        = 4;
                }
            }
            // Phase 1/4 (animating): ignore flipper presses
        }

        // ------------------------------------------------------------
        // Activate buttons: change test dungeon level and re-initialise
        // Left activate  → level - 1 (min 1)
        // Right activate → level + 1 (max 3)
        // ------------------------------------------------------------
        else if (inputMessage.inputId == IDI_LACTIVATE) {
            if (s_testDungeonLevel > 1) {
                s_testDungeonLevel--;
                pbeInitDungeonGrid(m_currentPlayer, s_testDungeonLevel);
            }
        }
        else if (inputMessage.inputId == IDI_RACTIVATE) {
            if (s_testDungeonLevel < 3) {
                s_testDungeonLevel++;
                pbeInitDungeonGrid(m_currentPlayer, s_testDungeonLevel);
            }
        }
    }

    // Always run mode-system bookkeeping
    pbeUpdateModeSystem(inputMessage, GetTickCountGfx());
}
