// Pinball_Table_ModeInTower.cpp:  PBTBL_INTOWER mode implementation
//   Handles the tower lock screen. Entered when IDI_TOWER sensor is triggered.
//   Reuses the main screen base rendering (background, scores, status) and
//   renders tower-specific content only within the main status/scoring area.
//   No exit condition yet; will be added in a future task.

// Copyright (c) 2025 Jeffrey D. Bock, unless otherwise noted. Licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.
// The license can be found here: <https://creativecommons.org/licenses/by-nc/4.0/>.
// Additional details can also be found in the license file in the root of the project.

#include "Pinball_Engine.h"
#include "Pinball_Table.h"
#include "PBDevice.h"
#include <cmath>
#include <cstdlib>

namespace {
struct D20Vec3 {
    float x, y, z;
};

// Continuous spin speeds (degrees/second) while the die is rolling.
static constexpr float kD20SpinSpeedXDegPerSec = 1800.0f;
static constexpr float kD20SpinSpeedYDegPerSec = 2160.0f;
static constexpr float kD20SpinSpeedZDegPerSec = 2520.0f;
static constexpr unsigned long kInTowerResolutionPointDelayMs = 175UL;
static constexpr unsigned long kInTowerHitPointFlashMs = 140UL;

static inline float d20DegToRad(float deg) { return deg * 0.01745329252f; }
static inline float d20RadToDeg(float rad) { return rad * 57.29577951f; }

// Per-value face orientation table.  Indexed by (value - 1); each entry is the
// instance rotation (degrees, applied as PB3D's Ry*Rx*Rz) that lays the face
// bearing that number flat against the screen, upright.
//
// >>> These values are GENERATED by the D20 calibration tool: enable
// >>> D20_CALIBRATION in PBBuildSwitch.h, press IDI_START in the InTower
// >>> screen, align each face, then copy the logged tuples here. <<<
// Calibrated face orientations (from the in-table D20 calibration tool).
struct D20Orient { float rx, ry, rz; };
static const D20Orient kD20Orient[20] = {
    {  10.815763f, -179.906509f, -179.491333f }, // value 1
    {  35.677311f,  -11.936172f,   52.136024f }, // value 2
    { -58.095261f,  124.965378f,  -19.375134f }, // value 3
    {  44.081123f,  -74.950966f,   64.636345f }, // value 4
    { -58.883102f, -126.040024f,   20.600882f }, // value 5
    {  44.989437f,   74.649902f,  -65.023010f }, // value 6
    { -52.598091f,  179.344482f,    0.824432f }, // value 7
    {  35.892860f,   11.180718f,  -53.342773f }, // value 8
    { -40.396957f, -130.069214f,  142.760300f }, // value 9
    {  40.360752f,   49.940521f,   37.228291f }, // value 10
    { -39.587296f,  129.546478f, -141.962646f }, // value 11
    {  39.580391f,  -50.237770f,  -37.821663f }, // value 12
    { -35.687405f,  168.093658f,  127.864983f }, // value 13
    {  52.635639f,   -0.675681f,  179.159546f }, // value 14
    { -44.022305f,  105.121124f,  115.380226f }, // value 15
    {  58.088268f,  -54.941887f, -160.575974f }, // value 16
    { -44.944668f, -105.397247f, -114.978516f }, // value 17
    {  58.924267f,   54.068447f,  159.550232f }, // value 18
    { -35.882080f, -168.842484f, -126.649902f }, // value 19
    { -10.803362f,    0.105199f,   -0.510858f }  // value 20
};

// Global yaw trim added to every face's Y rotation so the displayed face reads
// perfectly flat (shared by the initial render and the roll snap).
static const float kD20YawTrimDeg = 10.0f;

// Center-out fill order for the InTower warrior enemies on a staggered 5-row
// grid (rows 1=bottom..5=top; odd rows have 5 positions, even rows have 4
// staggered positions).  Enemy 0 takes the centre (row 3, pos 3); each later
// enemy fills outward in concentric rings until up to all 20 are placed.
struct EnemyCell { int row; int pos; };
static const EnemyCell kEnemyFillOrder[20] = {
    {3,3}, {3,4}, {3,2}, {2,3}, {2,2}, {4,3}, {4,2}, // centre + first ring
    {3,5}, {3,1}, {2,4}, {2,1}, {4,4}, {4,1},        // second ring
    {1,3}, {1,2}, {1,4}, {5,3}, {5,2}, {5,4}, {1,1}  // outer ring
};
}

// ========================================================================
// D20 CALIBRATION TOOL  ---  BEGIN
//   Self-contained, developer-only helper for generating kD20Orient[] above.
//   Gated entirely behind D20_CALIBRATION (see PBBuildSwitch.h).  To delete
//   the tool, remove this whole block plus the three small #ifdef D20_CALIBRATION
//   hooks in pbeUpdateStateInTower() / pbeRenderInTower() and the include below.
// ========================================================================
#ifdef D20_CALIBRATION
#include "3rdparty/cgltf.h"
#include <cstring>

namespace {

static constexpr int kD20CalibMaxFaces = 20;

struct D20CalibFace {
    D20Vec3 normal;       // model-space face normal (unit)
    D20Vec3 e1;           // in-plane basis vector 1
    D20Vec3 e2;           // in-plane basis vector 2 ( = normal x e1 )
};

static bool         s_d20CalibActive      = false; // calibration mode on/off
static bool         s_d20CalibParsed      = false; // model geometry parsed yet
static D20CalibFace s_d20CalibFaces[kD20CalibMaxFaces];
static int          s_d20CalibFaceCount   = 0;
static int          s_d20CalibPhase       = 0;     // 0 = orientation, 1 = number calibration
static float        s_d20CalibAngleOffset = 0.0f;  // hand-tuned in-plane rotation (rad)
static int          s_d20CalibFaceIdx     = 0;     // current face being aligned
static int          s_d20CalibCandIdx     = 0;     // which corner (0..2, 120deg apart)
static int          s_d20CalibValue       = 1;     // value assigned to this face

static inline D20Vec3 d20vSub(const D20Vec3& a, const D20Vec3& b)   { return { a.x - b.x, a.y - b.y, a.z - b.z }; }
static inline D20Vec3 d20vScale(const D20Vec3& a, float s)          { return { a.x * s, a.y * s, a.z * s }; }
static inline float   d20vDot(const D20Vec3& a, const D20Vec3& b)   { return a.x * b.x + a.y * b.y + a.z * b.z; }
static inline D20Vec3 d20vCross(const D20Vec3& a, const D20Vec3& b) { return { a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x }; }
static inline float   d20vLen(const D20Vec3& a)                     { return sqrtf(d20vDot(a, a)); }
static inline D20Vec3 d20vNorm(const D20Vec3& a)                    { float l = d20vLen(a); return (l > 1e-8f) ? d20vScale(a, 1.0f / l) : a; }

// Build the rotation that sends model-space normal n -> +Z (screen, toward the
// viewer) and the chosen up vector u -> +Y, then extract Euler angles matching
// PB3D's Ry*Rx*Rz application order.  Right vector r = u x n (right-handed).
static void d20CalibEuler(const D20Vec3& n, const D20Vec3& u,
                          float& rxDeg, float& ryDeg, float& rzDeg) {
    D20Vec3 nn = d20vNorm(n);
    D20Vec3 uu = d20vNorm(d20vSub(u, d20vScale(nn, d20vDot(u, nn)))); // orthogonalise up
    D20Vec3 rr = d20vNorm(d20vCross(uu, nn));

    // Rotation matrix rows are r, u, n.  For Ry*Rx*Rz:  R[1][2] = -sin(rx),
    // R[0][2]=sy*cx, R[2][2]=cy*cx, R[1][0]=cx*sz, R[1][1]=cx*cz.
    float rxr = asinf(fmaxf(-1.0f, fminf(1.0f, -uu.z)));
    float ryr, rzr;
    if (fabsf(cosf(rxr)) > 1e-4f) {
        ryr = atan2f(rr.z, nn.z);
        rzr = atan2f(uu.x, uu.y);
    } else {
        ryr = atan2f(-nn.x, rr.x);
        rzr = 0.0f;
    }
    rxDeg = d20RadToDeg(rxr);
    ryDeg = d20RadToDeg(ryr);
    rzDeg = d20RadToDeg(rzr);
}

// Parse d20dice.glb, cluster triangles into faces by normal, keep the 20
// largest-area clusters, and for each derive an in-plane basis plus the angle
// toward one triangle corner.  Returns true on success.
static bool d20CalibParseModel() {
    if (s_d20CalibParsed) return (s_d20CalibFaceCount > 0);
    s_d20CalibParsed = true;
    s_d20CalibFaceCount = 0;

    const char* path = "src/user/resources/3d/d20dice.glb";
    cgltf_options options;
    memset(&options, 0, sizeof(options));
    cgltf_data* data = nullptr;
    if (cgltf_parse_file(&options, path, &data) != cgltf_result_success) return (false);
    if (cgltf_load_buffers(&options, data, path) != cgltf_result_success) { cgltf_free(data); return (false); }

    // Cluster accumulators
    struct Cluster {
        D20Vec3 nSum;     // area-weighted normal sum
        D20Vec3 cSum;     // area-weighted centroid sum
        float   area;     // total area
    };
    static Cluster clusters[256];
    int clusterCount = 0;

    // First pass: accumulate clusters
    for (cgltf_size mi = 0; mi < data->meshes_count; ++mi) {
        cgltf_mesh* mesh = &data->meshes[mi];
        for (cgltf_size pi = 0; pi < mesh->primitives_count; ++pi) {
            cgltf_primitive* prim = &mesh->primitives[pi];
            if (prim->type != cgltf_primitive_type_triangles) continue;
            cgltf_accessor* posAcc = nullptr;
            for (cgltf_size ai = 0; ai < prim->attributes_count; ++ai) {
                if (prim->attributes[ai].type == cgltf_attribute_type_position) { posAcc = prim->attributes[ai].data; break; }
            }
            if (!posAcc) continue;
            cgltf_size triCount = prim->indices ? (prim->indices->count / 3) : (posAcc->count / 3);
            for (cgltf_size t = 0; t < triCount; ++t) {
                cgltf_size i0, i1, i2;
                if (prim->indices) {
                    i0 = cgltf_accessor_read_index(prim->indices, t * 3 + 0);
                    i1 = cgltf_accessor_read_index(prim->indices, t * 3 + 1);
                    i2 = cgltf_accessor_read_index(prim->indices, t * 3 + 2);
                } else { i0 = t * 3; i1 = t * 3 + 1; i2 = t * 3 + 2; }
                D20Vec3 v0, v1, v2;
                cgltf_accessor_read_float(posAcc, i0, &v0.x, 3);
                cgltf_accessor_read_float(posAcc, i1, &v1.x, 3);
                cgltf_accessor_read_float(posAcc, i2, &v2.x, 3);
                D20Vec3 cr = d20vCross(d20vSub(v1, v0), d20vSub(v2, v0));
                float area2 = d20vLen(cr);
                if (area2 < 1e-9f) continue;
                D20Vec3 nrm = d20vScale(cr, 1.0f / area2);
                D20Vec3 cen = d20vScale(D20Vec3{ v0.x + v1.x + v2.x, v0.y + v1.y + v2.y, v0.z + v1.z + v2.z }, 1.0f / 3.0f);
                float area = area2 * 0.5f;

                int found = -1;
                for (int c = 0; c < clusterCount; ++c) {
                    D20Vec3 cn = d20vNorm(clusters[c].nSum);
                    if (d20vDot(cn, nrm) > 0.95f) { found = c; break; }
                }
                if (found < 0 && clusterCount < 256) { found = clusterCount++; clusters[found] = { {0,0,0}, {0,0,0}, 0.0f }; }
                if (found >= 0) {
                    clusters[found].nSum   = D20Vec3{ clusters[found].nSum.x + nrm.x * area, clusters[found].nSum.y + nrm.y * area, clusters[found].nSum.z + nrm.z * area };
                    clusters[found].cSum   = D20Vec3{ clusters[found].cSum.x + cen.x * area, clusters[found].cSum.y + cen.y * area, clusters[found].cSum.z + cen.z * area };
                    clusters[found].area  += area;
                }
            }
        }
    }

    // Keep the 20 largest-area clusters
    int order[256];
    for (int i = 0; i < clusterCount; ++i) order[i] = i;
    for (int i = 0; i < clusterCount; ++i)
        for (int j = i + 1; j < clusterCount; ++j)
            if (clusters[order[j]].area > clusters[order[i]].area) { int tmp = order[i]; order[i] = order[j]; order[j] = tmp; }
    int keep = clusterCount < kD20CalibMaxFaces ? clusterCount : kD20CalibMaxFaces;

    for (int k = 0; k < keep; ++k) {
        D20Vec3 n = d20vNorm(clusters[order[k]].nSum);
        // Build an arbitrary in-plane basis.  The exact in-plane rotation that
        // makes the bottom edge horizontal is dialed in by hand in the
        // orientation phase (s_d20CalibAngleOffset), not estimated from geometry.
        D20Vec3 ref = (fabsf(n.y) < 0.9f) ? D20Vec3{ 0, 1, 0 } : D20Vec3{ 1, 0, 0 };
        D20Vec3 e1 = d20vNorm(d20vCross(n, ref));
        D20Vec3 e2 = d20vNorm(d20vCross(n, e1));
        s_d20CalibFaces[k].normal = n;
        s_d20CalibFaces[k].e1 = e1;
        s_d20CalibFaces[k].e2 = e2;
    }
    s_d20CalibFaceCount = keep;

    cgltf_free(data);
    return (s_d20CalibFaceCount > 0);
}

// Current candidate orientation for the face/corner the user is inspecting.
static void d20CalibCurrentOrient(float& rxDeg, float& ryDeg, float& rzDeg) {
    if (s_d20CalibFaceCount <= 0) { rxDeg = ryDeg = rzDeg = 0.0f; return; }
    const D20CalibFace& f = s_d20CalibFaces[s_d20CalibFaceIdx % s_d20CalibFaceCount];
    float ang = s_d20CalibAngleOffset + (float)s_d20CalibCandIdx * 1.04719755f; // hand-tuned offset + 60 deg steps
    D20Vec3 up = { f.e1.x * cosf(ang) + f.e2.x * sinf(ang),
                   f.e1.y * cosf(ang) + f.e2.y * sinf(ang),
                   f.e1.z * cosf(ang) + f.e2.z * sinf(ang) };
    d20CalibEuler(f.normal, up, rxDeg, ryDeg, rzDeg);
}

}
#endif // D20_CALIBRATION
// ========================================================================
// D20 CALIBRATION TOOL  ---  END
// ========================================================================

// ========================================================================
// PBTBL_INTOWER: Load Function
// ========================================================================

bool PBEngine::pbeLoadInTower() {

    if (m_inTowerLoaded) return (true);

    // InTower reuses the main screen background resources; ensure they are loaded
    if (!pbeLoadMainScreen()) return (false);

    m_TowerClimbId = gfxLoadSprite("TowerClimb", "src/user/resources/textures/towerclimb.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerClimbId, 80, 80, 160, 255);

    // Load dungeon door grid sprites
    m_DoorOpenId = gfxLoadSprite("DoorOpen", "src/user/resources/textures/dooropen.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorOpenId, 255, 255, 255, 255);

    m_DoorClosedId = gfxLoadSprite("DoorClosed", "src/user/resources/textures/doorclosed.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorClosedId, 255, 255, 255, 255);

    m_DoorBlockedId = gfxLoadSprite("DoorBlocked", "src/user/resources/textures/doorblocked.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorBlockedId, 255, 255, 255, 255);

    m_DoorWall1Id = gfxLoadSprite("DoorWall1", "src/user/resources/textures/doorwall1.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorWall1Id, 255, 255, 255, 255);

    m_DoorWall2Id = gfxLoadSprite("DoorWall2", "src/user/resources/textures/doorwall2.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorWall2Id, 255, 255, 255, 255);

    m_DoorStairsId = gfxLoadSprite("DoorStairs", "src/user/resources/textures/doorstairs.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorStairsId, 255, 255, 255, 255);

    // Load side mini-tower sprites
    m_TowerSmallTopId = gfxLoadSprite("TowerSmallTop", "src/user/resources/textures/towersmalltop.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerSmallTopId, 255, 255, 255, 255);

    m_TowerSmallOpenId = gfxLoadSprite("TowerSmallOpen", "src/user/resources/textures/towersmallopen.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerSmallOpenId, 255, 255, 255, 255);

    m_TowerSmallClosedId = gfxLoadSprite("TowerSmallClosed", "src/user/resources/textures/towersmallclosed.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerSmallClosedId, 255, 255, 255, 255);

    m_TowerSectionId = gfxLoadSprite("TowerSection", "src/user/resources/textures/towersmallsection.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_TowerSectionId, 255, 255, 255, 255);

    // Load dungeon floor tile sprites
    m_DoorLeftId  = gfxLoadSprite("DoorFloorLeft",  "src/user/resources/textures/doorfloorleft.png",  GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorLeftId,  255, 255, 255, 255);

    m_DoorRightId = gfxLoadSprite("DoorFloorRight", "src/user/resources/textures/doorfloorright.png", GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorRightId, 255, 255, 255, 255);

    m_DoorMidId   = gfxLoadSprite("DoorFloorMid",   "src/user/resources/textures/doorfloormid.png",   GFX_PNG, GFX_NOMAP, GFX_CENTER, true, true);
    gfxSetColor(m_DoorMidId,   255, 255, 255, 255);

    m_inTowerAvatarId = gfxLoadTileSprite("InTowerAvatar", "src/user/resources/textures/avatarsprite.png",
                                         GFX_PNG, GFX_CENTER, true, 128, 128);
    if (m_inTowerAvatarId != NOSPRITE) {
        gfxSetSelectedTile(m_inTowerAvatarId, 0);
        gfxSetColor(m_inTowerAvatarId, 255, 255, 255, 255);
    } else {
        pbeSendConsole("WARNING: Failed to load avatarsprite.png");
    }

    if (m_DoorOpenId == NOSPRITE || m_DoorClosedId == NOSPRITE || m_DoorBlockedId == NOSPRITE ||
        m_DoorWall1Id == NOSPRITE || m_DoorWall2Id == NOSPRITE || m_DoorStairsId == NOSPRITE ||
        m_TowerSmallTopId == NOSPRITE || m_TowerSmallOpenId == NOSPRITE ||
        m_TowerSmallClosedId == NOSPRITE || m_TowerSectionId == NOSPRITE ||
        m_DoorLeftId == NOSPRITE || m_DoorRightId == NOSPRITE || m_DoorMidId == NOSPRITE) {
        pbeSendConsole("ERROR: Failed to load InTower door sprites");
        return (false);
    }

    // Load the InTower d20 model once and keep a persistent instance.
    if (!m_inTowerD20Loaded) {
        m_inTowerD20ModelId = pb3dLoadModel("src/user/resources/3d/d20dice.glb");
        if (m_inTowerD20ModelId == 0) {
            pbeSendConsole("WARNING: Failed to load d20dice.glb");
        } else {
            m_inTowerD20InstanceId = pb3dCreateInstance(m_inTowerD20ModelId);
            pb3dSetInstanceScale(m_inTowerD20InstanceId, 0.63f);
            pb3dSetInstanceVisible(m_inTowerD20InstanceId, true);
            m_inTowerD20Value = 1;
            m_inTowerD20RollState = 0;
            // Show value 1 face-up using its calibrated tuple (+ global yaw trim).
            m_inTowerD20RotX = kD20Orient[0].rx;
            m_inTowerD20RotY = kD20Orient[0].ry + kD20YawTrimDeg;
            m_inTowerD20RotZ = kD20Orient[0].rz;
            pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
            m_inTowerD20Loaded = true;
        }
    }

    // Load the warrior enemy tile sprite (256x256 tiles) and create 20 instances.
    // Tiles 0-2 are one walk cycle, tiles 3-4 another; each enemy uses one range.
    if (!m_inTowerEnemyLoaded) {
        static constexpr float kInTowerEnemyScale = 0.6f; // 2x the original 0.4, less 25%
        m_inTowerEnemyBaseId = gfxLoadTileSprite("WarriorEnemy", "src/user/resources/textures/warriortilesmall.png",
                                                 GFX_PNG, GFX_CENTER, true, 256, 256);
        if (m_inTowerEnemyBaseId == NOSPRITE) {
            pbeSendConsole("WARNING: Failed to load warriortilesmall.png");
        } else {
            bool allInstancesOk = true;
            for (int i = 0; i < 20; i++) {
                m_inTowerEnemyInstanceIds[i] = gfxInstanceSprite(m_inTowerEnemyBaseId);
                if (m_inTowerEnemyInstanceIds[i] == NOSPRITE) { allInstancesOk = false; break; }
                gfxSetScaleFactor(m_inTowerEnemyInstanceIds[i], kInTowerEnemyScale, false);
                gfxSetSelectedTile(m_inTowerEnemyInstanceIds[i], 0);
            }
            m_inTowerEnemyLoaded = allInstancesOk;
        }
    }

    // Ensure the slash death-overlay sprites are resident.  These are loaded by
    // the main table state; gfxLoadSprite is idempotent by name, so these calls
    // just return the existing IDs (no new instances) when already loaded.
    m_PBTBLSlash1Id = gfxLoadSprite("Slash1", "src/user/resources/textures/slash1.png",
                                    GFX_PNG, GFX_NOMAP, GFX_UPPERLEFT, true, true);
    m_PBTBLSlash2Id = gfxLoadSprite("Slash2", "src/user/resources/textures/slash2.png",
                                    GFX_PNG, GFX_NOMAP, GFX_UPPERLEFT, true, true);

    m_inTowerLoaded = true;
    return (true);
}

// ========================================================================
// PBTBL_INTOWER: Dungeon Grid Initialization
// ========================================================================

// File-scope test variable: tracks which dungeon level is displayed in InTower
// (for testing only; not tied to player-state dungeonLevel)
static int s_testDungeonLevel = 1;

// Initialize the dungeon grid for a given player at the specified level.
//   playerNum : 0-3 (clamped)
//   level     : 1=linear 3-floor (col 1 only)
//               2=4-floor 2-col (cols 1-2, random ladders)
//               3=5-floor 3-col (cols 0-2, random ladders)
void PBEngine::pbeInitDungeonGrid(int playerNum, int level) {

    // Clamp inputs to valid ranges
    if (playerNum < 0) playerNum = 0;
    if (playerNum > 3) playerNum = 3;
    if (level < 1) level = 1;
    if (level > 3) level = 3;

    TowerDungeonGrid& grid = m_playerStates[playerNum].dungeonGrid;

    // Clear all cells to DOOR_NONE
    grid = TowerDungeonGrid();

    if (level == 1) {
        // ----------------------------------------------------------------
        // Level 1: linear 3-floor path, centre column only, no randomness
        // ----------------------------------------------------------------
        const int col = 1;
        const int numRows = 3;
        for (int r = 0; r < numRows; r++) {
            grid.cells[r][col].state = DoorState::DOOR_CLOSED;
        }
        // Ladders on floors 0 and 1; dragon lair on floor 2
        grid.cells[0][col].hasLadder = true;
        grid.cells[0][col].role = TowerDoorRole::STAIRCASE;
        grid.cells[1][col].hasLadder = true;
        grid.cells[1][col].role = TowerDoorRole::STAIRCASE;
        grid.cells[2][col].isDragonLair = true;
        grid.cells[2][col].hasLadder = true;
        grid.cells[2][col].role = TowerDoorRole::DRAGON;

    } else if (level == 2) {
        // ----------------------------------------------------------------
        // Level 2: 4-floor path, cols 1-2, random ladder per row
        // ----------------------------------------------------------------
        const int activeCols[2] = { 1, 2 };
        const int numActiveCols  = 2;
        const int numRows        = 4;

        for (int r = 0; r < numRows; r++) {
            for (int c = 0; c < numActiveCols; c++) {
                grid.cells[r][activeCols[c]].state = DoorState::DOOR_CLOSED;
            }
        }
        // One random ladder per non-top row
        for (int r = 0; r < numRows - 1; r++) {
            int pick = rand() % numActiveCols;
            DoorCell& stair = grid.cells[r][activeCols[pick]];
            stair.hasLadder = true;
            stair.role = TowerDoorRole::STAIRCASE;
        }
        // One random dragon lair on top row
        {
            int pick = rand() % numActiveCols;
            DoorCell& dragon = grid.cells[numRows - 1][activeCols[pick]];
            dragon.isDragonLair = true;
            dragon.hasLadder = true;
            dragon.role = TowerDoorRole::DRAGON;
        }

    } else {
        // ----------------------------------------------------------------
        // Level 3: 5-floor path, all 3 cols (0-2), random ladder per row
        // ----------------------------------------------------------------
        const int activeCols[3] = { 0, 1, 2 };
        const int numActiveCols  = 3;
        const int numRows        = 5;

        for (int r = 0; r < numRows; r++) {
            for (int c = 0; c < numActiveCols; c++) {
                grid.cells[r][activeCols[c]].state = DoorState::DOOR_CLOSED;
            }
        }
        // One random ladder per non-top row
        for (int r = 0; r < numRows - 1; r++) {
            int pick = rand() % numActiveCols;
            DoorCell& stair = grid.cells[r][activeCols[pick]];
            stair.hasLadder = true;
            stair.role = TowerDoorRole::STAIRCASE;
        }
        // One random dragon lair on top row
        {
            int pick = rand() % numActiveCols;
            DoorCell& dragon = grid.cells[numRows - 1][activeCols[pick]];
            dragon.isDragonLair = true;
            dragon.hasLadder = true;
            dragon.role = TowerDoorRole::DRAGON;
        }
    }

    // Randomize hasTorch for every active cell (determines doorwall1 vs doorwall2
    // on the wall to the right of that door).  Far-right column cells are also
    // randomized even though their wall is never rendered.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                grid.cells[r][c].hasTorch = (rand() % 2 == 1);
            }
        }
    }

    // Assign a random enemy count per active room, scaled by level:
    //   Level 1: 1-8   Level 2: 8-12   Level 3: 6-20
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                if (level == 1)      grid.cells[r][c].monsterCount = (rand() % 8) + 1;   // 1-8
                else if (level == 2) grid.cells[r][c].monsterCount = (rand() % 5) + 8;   // 8-12
                else                 grid.cells[r][c].monsterCount = (rand() % 15) + 6;  // 6-20
                grid.cells[r][c].originalMonsterCount = grid.cells[r][c].monsterCount;
            }
        }
    }

    // Challenge requirements are persisted on their staircase doors.  Shuffle
    // the party once, then repeat a member only after every member was used.
    const int challengeLevels[3][4] = { { 1, 1, 0, 0 }, { 1, 1, 2, 0 }, { 1, 2, 2, 3 } };
    TowerChampion champions[3] = { TowerChampion::KNIGHT, TowerChampion::PRIEST, TowerChampion::RANGER };
    for (int i = 2; i > 0; --i) {
        int pick = rand() % (i + 1);
        TowerChampion swap = champions[i];
        champions[i] = champions[pick];
        champions[pick] = swap;
    }
    int challengeIndex = 0;
    for (int r = 0; r < 5; ++r) {
        for (int c = 0; c < 3; ++c) {
            DoorCell& cell = grid.cells[r][c];
            if (cell.role == TowerDoorRole::STAIRCASE) {
                cell.requiredChampion = champions[challengeIndex % 3];
                cell.challengeLevel = challengeLevels[level - 1][challengeIndex];
                challengeIndex++;
            }
        }
    }

    // Signal the render function to restart the zoom-in animation
    m_dungeonGridAnimPending = true;

    // Return the dungeon to fullscreen presentation phase
    m_inTowerDungeonPhase = 0;
    m_inTowerDoorJustOpened = false;
    m_inTowerSelectedDoor = -1;
}

// ========================================================================
// PBTBL_INTOWER: Dungeon Grid Render
// ========================================================================

// Render the dungeon door grid for the current player.
//   scale   : final/target scale factor (1.0 = native image size)
//   centerX : screen X of the grid centre
//   centerY : screen Y of the grid centre
//   animate : if true, zoom from 0 to scale over 2 s; reset triggered by
//             pbeInitDungeonGrid setting m_dungeonGridAnimPending
void PBEngine::pbeRenderDungeonGrid(float scale, int centerX, int centerY,
                                    bool animate,
                                    unsigned long currentTick, unsigned long /*lastTick*/) {

    TowerDungeonGrid& grid = m_playerStates[m_currentPlayer].dungeonGrid;

    // ---- Animated scale ------------------------------------------------
    // When animate=true, pbeInitDungeonGrid sets m_dungeonGridAnimPending.
    // The first render call after that latches the start tick and the grid
    // zooms from scale=0 to the target scale over 2000 ms.
    float renderScale = scale;
    if (animate) {
        if (m_dungeonGridAnimPending) {
            m_dungeonGridAnimStartTick = currentTick;
            m_dungeonGridAnimPending   = false;
        }
        float t = (currentTick >= m_dungeonGridAnimStartTick)
                  ? (float)(currentTick - m_dungeonGridAnimStartTick) / 1000.0f
                  : 0.0f;
        if (t > 1.0f) t = 1.0f;

        // Ease-out quadratic: scale grows fast early so the grid is nearly
        // full-size well before it arrives — only a small pop at the end.
        float tScale    = 1.0f - (1.0f - t) * (1.0f - t);
        renderScale     = scale * tScale;

        // Swirl path: begins at the bottom-centre door position and spirals
        // CCW into the final centre over 1 second.
        //   bottomOffset = distance from grid centre to row-0 (bottom door)
        //   using final scale so the start lines up with the door's real position.
        float finalDoorH   = (float)gfxGetBaseHeight(m_DoorOpenId) * scale;
        float finalRowStep = finalDoorH * 1.25f;          // doorH + doorH/4
        float bottomOffset = 2.0f * finalRowStep;         // 2 rows below centre

        float offsetMag = (1.0f - t) * bottomOffset;
        // CCW revolution: PI/2 (below) -> PI/2 + 2PI
        float angle = 1.5707963f + t * 6.2831853f;
        float rawX  = cosf(angle) * offsetMag * 0.4f;    // Narrow left swing to ~40% of orbit radius
        float rawY  = sinf(angle) * offsetMag;

        // Never shift right of the final position — keeps the grid inside the tower image
        float startShiftX = (1.0f - t) * 210.0f;  // +210 px right at t=0, fades to 0 at t=1
        float startShiftY = (1.0f - t) * -80.0f;  // -80 px up   at t=0, fades to 0 at t=1
        centerX += (int)(rawX < 0.0f ? rawX : 0.0f) + (int)startShiftX;
        centerY += (int)rawY + (int)startShiftY;
    }

    // ---- Layout metrics (all use renderScale for consistent zoom) -------
    int doorW  = (int)(gfxGetBaseWidth(m_DoorOpenId)  * renderScale);
    int doorH  = (int)(gfxGetBaseHeight(m_DoorOpenId) * renderScale);

    int gapH    = (int)((doorH / 4 + 10) * 0.5625f);
    int rowStep = doorH + gapH;

    int wallNativeW  = (int)gfxGetBaseWidth(m_DoorWall1Id);
    int colGap       = (int)(wallNativeW * renderScale / 4.0f);
    int colStep      = doorW + colGap;

    // ---- Row positions (centred at centerY) ----------------------------
    int rowPositions[5];
    int gridTop = centerY - (2 * rowStep) - 10;
    for (int r = 0; r < 5; r++) {
        rowPositions[r] = gridTop + (4 - r) * rowStep;
    }

    // ---- Column positions (smart centering for even / odd active cols) --
    // Scan active column range so the grid is always centred at centerX
    // regardless of whether an even or odd number of columns are in use.
    //   Odd  (1 or 3 cols): centre lands on the middle column.
    //   Even (2 cols)     : centre sits in the gap between the two columns.
    int minActiveCol = 3, maxActiveCol = -1;
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                if (c < minActiveCol) minActiveCol = c;
                if (c > maxActiveCol) maxActiveCol = c;
            }
        }
    }
    if (maxActiveCol < 0) { minActiveCol = 1; maxActiveCol = 1; }
    float centerColIdx = (minActiveCol + maxActiveCol) / 2.0f;

    int colPositions[3];
    for (int c = 0; c < 3; c++) {
        colPositions[c] = centerX + (int)((c - centerColIdx) * colStep);
    }

    // Pre-compute floor tile dimensions (used in Pass 2)
    float floorScale    = renderScale * 0.525f;
    int floorTileH      = (int)(gfxGetBaseHeight(m_DoorLeftId)  * floorScale);
    int floorTileWLeft  = (int)(gfxGetBaseWidth(m_DoorLeftId)   * floorScale);
    int floorTileWMid   = (int)(gfxGetBaseWidth(m_DoorMidId)    * floorScale);
    int floorTileWRight = (int)(gfxGetBaseWidth(m_DoorRightId)  * floorScale);

    // ---- Pass 1: Floor tiles (lowest layer — doorleft | doormid × N | doorright) --
    // For each active row, render a contiguous floor strip under its doors.
    // The strip spans from the left edge of the leftmost active column to the
    // right edge of the rightmost active column in that row.
    for (int r = 0; r < 5; r++) {
        int minColRow = 3, maxColRow = -1;
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state != DoorState::DOOR_NONE) {
                if (c < minColRow) minColRow = c;
                if (c > maxColRow) maxColRow = c;
            }
        }
        if (maxColRow < 0) continue;

        int floorY     = rowPositions[r] + doorH / 2 + floorTileH / 2 - (int)(doorH * 0.25f);
        int floorLeft  = colPositions[minColRow] - doorW / 2;
        int floorRight = colPositions[maxColRow] + doorW / 2;

        // Left cap (shifted inward by 5% of doorW)
        gfxRenderSprite(m_DoorLeftId,  floorLeft  + (int)(doorW * 0.05f), floorY, floorScale, 0.0f);
        // Right cap (shifted inward by 5% of doorW)
        gfxRenderSprite(m_DoorRightId, floorRight - (int)(doorW * 0.05f), floorY, floorScale, 0.0f);
        // Middle tiles: step by floorTileWMid across the gap between left and right caps
        if (floorTileWMid > 0) {
            int midStart = floorLeft  + floorTileWLeft  / 2;
            int midEnd   = floorRight - floorTileWRight / 2;
            int midStep  = (int)(floorTileWMid * 0.85f); // 15% overlap to close tile gaps
            for (int mx = midStart + floorTileWMid / 2; mx < midEnd; mx += midStep) {
                gfxRenderSprite(m_DoorMidId, mx, floorY, floorScale, 0.0f);
            }
        }
    }

    // ---- Pass 2: Walls --------------------------------------------------
    // Render the horizontal wall connector between adjacent door columns.
    // Use doorwall1 (torch) or doorwall2 per hasTorch.
    // Shifted 5 pixels left from the exact midpoint and 10% of doorH + 10px downward.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 2; c++) {
            if (grid.cells[r][c].state     != DoorState::DOOR_NONE &&
                grid.cells[r][c + 1].state != DoorState::DOOR_NONE) {
                int wallX = (colPositions[c] + colPositions[c + 1]) / 2 - 5;
                int wallY = rowPositions[r] + (int)(doorH * 0.07f) + 2;
                unsigned int wallSprite = grid.cells[r][c].hasTorch ? m_DoorWall1Id : m_DoorWall2Id;
                gfxRenderSprite(wallSprite, wallX, wallY, renderScale, 0.0f);
            }
        }
    }

    const auto resolvedDoorState = [&](int row, int col) -> DoorState {
        return grid.cells[row][col].state;
    };

    // ---- Pass 3: Blocked/Stairs overlays --------------------------------
    // For open doors, render doorstairs.png (shifted +6 px right) if the cell
    // has a ladder; otherwise render doorblocked.png at the original position.
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            const DoorState visualState = resolvedDoorState(r, c);
            if (visualState == DoorState::DOOR_OPEN) {
                if (grid.cells[r][c].hasLadder) {
                    gfxRenderSprite(m_DoorStairsId,
                                    colPositions[c] + 6,
                                    rowPositions[r],
                                    renderScale * 0.8f, 0.0f);
                } else {
                    gfxRenderSprite(m_DoorBlockedId,
                                    colPositions[c],
                                    rowPositions[r],
                                    renderScale * 0.8f, 0.0f);
                }
            }
        }
    }

    // ---- Pass 4: Doors -------------------------------------------------
    for (int r = 0; r < 5; r++) {
        for (int c = 0; c < 3; c++) {
            if (grid.cells[r][c].state == DoorState::DOOR_NONE) continue;
            const DoorState visualState = resolvedDoorState(r, c);
            unsigned int spriteId = (visualState == DoorState::DOOR_OPEN)
                                    ? m_DoorOpenId : m_DoorClosedId;
            gfxRenderSprite(spriteId, colPositions[c], rowPositions[r], renderScale, 0.0f);
        }
    }

    // ---- Pass 5: Door-opening avatar ------------------------------------
    if (m_inTowerAvatarId != NOSPRITE &&
        (m_inTowerDungeonPhase == 0 || m_inTowerDungeonPhase == 1 ||
         m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3)) {
        int avatarRow = -1;
        int avatarCol = -1;

        if ((m_inTowerDoorJustOpened || m_inTowerDungeonPhase != 0) &&
            m_inTowerOpenedRow >= 0 && m_inTowerOpenedCol >= 0) {
            avatarRow = m_inTowerOpenedRow;
            avatarCol = m_inTowerOpenedCol;
        } else {
            int selectedRow = m_playerStates[m_currentPlayer].dungeonFloor - 1;
            int selectedCol = m_inTowerSelectedDoor;
            if (selectedRow >= 0 && selectedRow < 5 && selectedCol >= 0 && selectedCol < 3 &&
                grid.cells[selectedRow][selectedCol].state != DoorState::DOOR_NONE) {
                avatarRow = selectedRow;
                avatarCol = selectedCol;
            } else {
                for (int c = 2; c >= 0; --c) {
                    if (selectedRow >= 0 && selectedRow < 5 &&
                        grid.cells[selectedRow][c].state != DoorState::DOOR_NONE) {
                        avatarRow = selectedRow;
                        avatarCol = c;
                        m_inTowerSelectedDoor = c;
                        break;
                    }
                }
            }
        }
        const bool hideStairAvatarForCombat =
            avatarRow >= 0 && avatarCol >= 0 &&
            (m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT ||
             m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT) &&
            grid.cells[avatarRow][avatarCol].hasLadder;
        if (avatarRow >= 0 && avatarCol >= 0 &&
            !hideStairAvatarForCombat) {
            float vanish = 0.0f;
            unsigned long avatarAgeMs = 0;
            if (m_inTowerDoorJustOpened) {
                avatarAgeMs = currentTick - m_inTowerAvatarOpenTick;
                if (avatarAgeMs > 1000UL) avatarAgeMs = 1000UL;
                vanish = (float)avatarAgeMs / 1000.0f;
            } else if (m_inTowerDungeonPhase != 0) {
                vanish = m_inTowerAvatarRoomProgress;
            }

            const float avatarAgeSec = (float)currentTick / 1000.0f;
            const float sequence = avatarAgeSec / 0.5f;
            const unsigned int frameIndex = (unsigned int)fmodf(sequence, 4.0f);
            gfxSetSelectedTile(m_inTowerAvatarId, frameIndex);

            const bool isStaircaseDoor = (avatarRow >= 0 && avatarCol >= 0 && grid.cells[avatarRow][avatarCol].hasLadder);
            const float avatarScale = renderScale * 0.75f * 1.40f * 0.95f * 0.85f;
            const int avatarAnchorOffset = (int)(35.0f * renderScale / 0.69f);
            const int baseAvatarY = rowPositions[avatarRow] + (int)(doorH * 0.62f) - avatarAnchorOffset;
            const int yShift = isStaircaseDoor ? 25 : 15;
            const int xShift = isStaircaseDoor ? 8 : 0;
            float compactRoomProgress = 0.0f;
            if (m_inTowerDungeonPhase == 1) {
                compactRoomProgress = (float)(currentTick - m_inTowerShrinkAnimStartTick) / 500.0f;
                if (compactRoomProgress > 1.0f) compactRoomProgress = 1.0f;
            } else if (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3) {
                compactRoomProgress = 1.0f;
            }
            const int roomOffsetY = !isStaircaseDoor
                                        ? (int)(10.0f * renderScale / 0.69f * compactRoomProgress) : 0;
            const int renderX = colPositions[avatarCol] + (int)(xShift * vanish);
            const int renderY = baseAvatarY - (int)(yShift * vanish) + roomOffsetY;
            const float endScale = isStaircaseDoor ? 0.40f : 0.75f;
            const float animatedScale = avatarScale * (endScale + (1.0f - endScale) * (1.0f - vanish));
            gfxRenderSprite(m_inTowerAvatarId, renderX, renderY, animatedScale, 0.0f);
        }
    }

    // ---- Pass 6: Side mini-tower (rendered to the right of the door grid) -------
    // Layout (bottom to top): TO, [TS, TC[i]] × (numFloors-1), TT
    //   TO  = towersmallopen.png  (always-open base at the very bottom)
    //   TS  = towersection.png    (connecting section; sits midway between each pair of key sprites)
    //   TC  = towersmallclosed/open.png  (gate; open when towerSectionOpen[i] is true)
    //   TT  = towersmalltop.png   (top cap)
    //
    // All Y positions are derived from the already-computed rowPositions and rowStep so the
    // tower scales and animates identically to the door grid in all phases.
    {
        // Determine highest active row (= numFloors - 1)
        int maxActiveRow = -1;
        for (int r = 0; r < 5; r++) {
            for (int c = 0; c < 3; c++) {
                if (grid.cells[r][c].state != DoorState::DOOR_NONE && r > maxActiveRow)
                    maxActiveRow = r;
            }
        }
        if (maxActiveRow < 0) maxActiveRow = 0; // safety guard
        int numFloors = maxActiveRow + 1;

        // Tower column X: shifted 20px closer to the doors than a full colStep offset, then +10% of doorW right
        int towerX = colPositions[maxActiveCol] + colStep - 20 + (int)(doorW * 0.1f);

        // Build an array of Y anchor positions for the key sprites:
        //   keyY[0]           = TO  (half a rowStep below floor 0)
        //   keyY[1..N-1]      = TC[0..N-2]  (midway between adjacent floor pairs)
        //   keyY[numFloors]   = TT  (half a rowStep above the top floor)
        int keyY[6]; // max N=5 → 6 entries
        keyY[0] = rowPositions[0] + rowStep / 2;
        for (int i = 0; i < numFloors - 1; i++) {
            keyY[i + 1] = (rowPositions[i] + rowPositions[i + 1]) / 2;
        }
        keyY[numFloors] = rowPositions[numFloors - 1] - rowStep / 2;

        // TO (always-open base)
        gfxRenderSprite(m_TowerSmallOpenId, towerX, keyY[0], renderScale, 0.0f);

        // For each TC: render TS at the midpoint between the preceding key sprite and TC,
        // then render TC itself.  This gives the sequence TO, TS, TC[0], TS, TC[1], ..., TT.
        for (int i = 0; i < numFloors - 1; i++) {
            // TS: vertically between keyY[i] (TO or previous TC) and keyY[i+1] (this TC)
            int tsY = (keyY[i] + keyY[i + 1]) / 2;
            gfxRenderSprite(m_TowerSectionId, towerX, tsY, renderScale, 0.0f);

            bool sectionOpen = grid.towerSectionOpen[i];
            unsigned int tcSprite = sectionOpen ? m_TowerSmallOpenId : m_TowerSmallClosedId;
            gfxRenderSprite(tcSprite, towerX, keyY[i + 1], renderScale, 0.0f);
        }

        // TS between the last TC and TT, then TT at the top cap
        gfxRenderSprite(m_TowerSectionId,  towerX, rowPositions[numFloors - 1], renderScale, 0.0f);
        gfxRenderSprite(m_TowerSmallTopId, towerX, keyY[numFloors],             renderScale, 0.0f);

        if (m_inTowerAvatarId != NOSPRITE &&
            m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT &&
            m_inTowerOpenedRow >= 0 && m_inTowerOpenedRow < numFloors - 1 &&
            m_inTowerOpenedCol >= 0 && m_inTowerOpenedCol < 3) {
            const float avatarAgeSec = (float)currentTick / 1000.0f;
            const unsigned int frameIndex = (unsigned int)fmodf(avatarAgeSec / 0.5f, 4.0f);
            gfxSetSelectedTile(m_inTowerAvatarId, frameIndex);
            gfxRenderSprite(m_inTowerAvatarId, towerX, keyY[m_inTowerOpenedRow + 1],
                            renderScale * 0.85f, 0.0f);
        }
    }
}

void PBEngine::pbeUpdateInTowerD20(unsigned long currentTick) {
    if (!m_inTowerD20Loaded) return;

#ifdef D20_CALIBRATION
    if (s_d20CalibActive) {
        // Calibration owns the orientation while active.
        float rx, ry, rz;
        d20CalibCurrentOrient(rx, ry, rz);
        pb3dSetInstanceRotation(m_inTowerD20InstanceId, rx, ry, rz);
        return;
    }
#endif

    if (m_inTowerD20RollState == 1) {
        // Spinning: advance all three axes continuously until the player stops it.
        float t = (currentTick >= m_inTowerD20SpinStartTick)
                ? (float)(currentTick - m_inTowerD20SpinStartTick) / 1000.0f : 0.0f;
        m_inTowerD20RotX = m_inTowerD20SpinBaseRotX + (kD20SpinSpeedXDegPerSec * t);
        m_inTowerD20RotY = m_inTowerD20SpinBaseRotY + (kD20SpinSpeedYDegPerSec * t);
        m_inTowerD20RotZ = m_inTowerD20SpinBaseRotZ + (kD20SpinSpeedZDegPerSec * t);
    }
    // RollState 0 (idle) and 2 (stopped) keep their current rotation; the stop
    // transition snaps to kD20Orient[value-1] in pbeUpdateStateInTower().

    pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
}

// ========================================================================
// PBTBL_INTOWER: Render Function
// ========================================================================

bool PBEngine::pbeRenderInTower(unsigned long currentTick, unsigned long lastTick, PBTBLInTowerScreenState subScreenState) {

    if (!pbeLoadInTower()) {
        pbeSendConsole("ERROR: Failed to load InTower screen resources");
        return (false);
    }

    pbGameState& player = m_playerStates[m_currentPlayer];
    TowerDungeonGrid& grid = player.dungeonGrid;
    if (m_inTowerFlowState == InTowerFlowState::TOWER_INIT) {
#if TEST_TOWER < 0 || TEST_TOWER > 3
#error "TEST_TOWER must be 0, 1, 2, or 3"
#endif
        if (player.towerNeedsReset) {
#if TEST_TOWER != 0
            player.knightJoined = true;
            player.priestJoined = true;
            player.rangerJoined = true;
        player.knightLevel = TEST_TOWER;
        player.priestLevel = TEST_TOWER;
        player.rangerLevel = TEST_TOWER;
        player.dungeonLevel = TEST_TOWER;
#endif
            pbeInitDungeonGrid(m_currentPlayer, player.dungeonLevel);
            player.towerNeedsReset = false;
            player.dungeonFloor = 1;
            player.towerResumeFloor = 1;
            player.towerResumeDoor = -1;
        }
        player.towerHitPoints = 20;
        m_inTowerSelectedDoor = player.towerResumeDoor;
        m_inTowerFlowState = InTowerFlowState::TOWER_CLIMB;
        m_inTowerFlowStateStartTick = currentTick;
    }

    pbeSetStatusText(0, "Climb the Tower!");
    if (m_inTowerFlowState == InTowerFlowState::TOWER_CLIMB) {
        pbeSetStatusText(1, "Flipper to select door, Activate to open!");
        if (m_inTowerDoorJustOpened && currentTick - m_inTowerAvatarOpenTick >= 750UL) {
            DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
            int enemies = door.monsterCount;
            if (enemies < 0) enemies = 0;
            if (enemies > 20) enemies = 20;
            m_inTowerEnemyCount = enemies;
            m_inTowerEnemyRemaining = enemies;
            m_inTowerRollEnemyCount = enemies;
            m_inTowerEnemiesNeedSpawn = enemies > 0;
            m_inTowerEnemiesActive = enemies > 0;
            unsigned long avatarEntryMs = currentTick - m_inTowerAvatarOpenTick;
            if (avatarEntryMs > 1000UL) avatarEntryMs = 1000UL;
            m_inTowerAvatarRoomProgress = (float)avatarEntryMs / 1000.0f;
            m_inTowerDoorJustOpened = false;
            m_inTowerD20RollState = 0;
            m_inTowerResolutionApplied = false;
            m_inTowerResolutionStep = 0;
            m_inTowerPendingDamage = 0;
            m_inTowerHitPointFlashTick = 0;
            for (int i = 0; i < 20; ++i) m_inTowerEnemyDeathTick[i] = 0;
            if (enemies == 0 && door.role == TowerDoorRole::STAIRCASE) {
                grid.towerSectionOpen[m_inTowerOpenedRow] = true;
                m_inTowerChallengeDoorOverrideActive = true;
                m_inTowerChallengeDoorOverrideRow = m_inTowerOpenedRow;
                m_inTowerChallengeDoorOverrideCol = m_inTowerOpenedCol;
                m_inTowerFlowState = InTowerFlowState::FLOOR_CHALLENGE_VIDEO;
                m_inTowerFlowStateStartTick = currentTick;
                m_inTowerDungeonPhase = 4;
                m_inTowerShrinkAnimStartTick = currentTick;
            } else if (enemies == 0 && door.role == TowerDoorRole::ORDINARY) {
                m_inTowerFlowState = InTowerFlowState::TOWER_CLIMB;
                m_inTowerFlowStateStartTick = currentTick;
                m_inTowerDungeonPhase = 0;
            } else {
                m_inTowerDungeonPhase = 1;
                m_inTowerShrinkAnimStartTick = currentTick;
                m_inTowerFlowState = InTowerFlowState::ROOM_FIGHT;
                m_inTowerFlowStateStartTick = currentTick;
            }
        }
    } else if (m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT) {
        const char* resolutionText = m_inTowerResolutionStep == 1 ? "Sword strikes remaining enemies..." :
                         m_inTowerResolutionStep == 2 ? "Shield blocks incoming damage..." :
                         m_inTowerResolutionStep == 3 ? "Resolving tower damage..." :
                         m_inTowerResolutionStep == 4 ? "Damage resolved..." :
                                     "Resolving battle...";
        pbeSetStatusText(1, m_inTowerD20RollState == 0 ? "Activate to roll the D20!" :
                            m_inTowerD20RollState == 1 ? "Activate to stop the D20!" : resolutionText);
    } else if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_VIDEO) {
        pbeSetStatusText(1, "Champion challenge incoming...");
        if (m_inTowerVideoSkipRequested) {
            m_inTowerVideoSkipRequested = false;
            DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
            bool joined = door.requiredChampion == TowerChampion::KNIGHT ? player.knightJoined :
                          door.requiredChampion == TowerChampion::PRIEST ? player.priestJoined : player.rangerJoined;
            if (!joined) {
                player.towerMissingChampion = true;
                door.state = DoorState::DOOR_CLOSED;
                grid.towerSectionOpen[m_inTowerOpenedRow] = false;
                m_inTowerChallengeDoorOverrideActive = false;
                m_inTowerChallengeDoorOverrideRow = -1;
                m_inTowerChallengeDoorOverrideCol = -1;
                m_inTowerFlowState = InTowerFlowState::EXIT_TOWER;
                m_inTowerFlowStateStartTick = currentTick;
            } else {
                m_inTowerChallengeMode = true;
                m_inTowerEnemyCount = 0;
                m_inTowerEnemyRemaining = 0;
                m_inTowerRollEnemyCount = 0;
                m_inTowerEnemiesActive = false;
                m_inTowerD20RollState = 0;
                m_inTowerResolutionApplied = false;
                m_inTowerResolutionStep = 0;
                m_inTowerPendingDamage = 0;
                m_inTowerDungeonPhase = 1;
                m_inTowerShrinkAnimStartTick = currentTick;
                m_inTowerFlowState = InTowerFlowState::FLOOR_CHALLENGE_FIGHT;
                m_inTowerFlowStateStartTick = currentTick;
                m_inTowerChallengeDoorOverrideActive = true;
                m_inTowerChallengeDoorOverrideRow = m_inTowerOpenedRow;
                m_inTowerChallengeDoorOverrideCol = m_inTowerOpenedCol;
            }
        }
    } else if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT) {
        pbeSetStatusText(1, m_inTowerD20RollState == 0 ? "Activate to attempt challenge!" :
                            m_inTowerD20RollState == 1 ? "Activate to stop the D20!" : "Resolving challenge...");
    } else if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_SUCCESS) {
        pbeSetStatusText(1, "Challenge complete!");
        if (currentTick - m_inTowerFlowStateStartTick >= 1500UL) {
            grid.towerSectionOpen[m_inTowerOpenedRow] = true;
            player.dungeonFloor++;
            player.towerResumeFloor = player.dungeonFloor;
            player.towerResumeDoor = -1;
            m_inTowerSelectedDoor = -1;
            m_inTowerChallengeMode = false;
            m_inTowerChallengeDoorOverrideActive = false;
            m_inTowerChallengeDoorOverrideRow = -1;
            m_inTowerChallengeDoorOverrideCol = -1;
            m_inTowerFlowState = InTowerFlowState::TOWER_CLIMB;
            m_inTowerDungeonPhase = 0;
        }
    } else if (m_inTowerFlowState == InTowerFlowState::EXIT_TOWER) {
        pbeSetStatusText(1, player.towerMissingChampion ? "Missing Champion" : "Defeated! Try Again");
        if (currentTick - m_inTowerFlowStateStartTick >= 2000UL) {
            player.towerMissingChampion = false;
            pbeExitMode(PBTableMode::MODE_INTOWER, currentTick);
            pbeEnterMode(PBTableMode::MODE_NORMAL_PLAY, currentTick);
            m_tableState = PBTableState::PBTBL_MAIN;
        }
    } else if (m_inTowerFlowState == InTowerFlowState::DRAGON_VIDEO) {
        pbeSetStatusText(1, "Dragon discovered!");
        if (m_inTowerVideoSkipRequested) {
            m_inTowerVideoSkipRequested = false;
            m_dragonMultiballResult = 0;
            m_tableState = PBTableState::PBTBL_DRAGONMULTIBALL;
        }
    }

    if ((m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT ||
         m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT) &&
        m_inTowerD20RollState == 2 && !m_inTowerResolutionApplied &&
        m_inTowerResolutionStep == 0 &&
        currentTick - m_inTowerD20StopTick >= 750UL) {
        DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
        if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT) {
            m_inTowerResolutionApplied = true;
            const int championLevel = door.requiredChampion == TowerChampion::KNIGHT ? player.knightLevel :
                                      door.requiredChampion == TowerChampion::PRIEST ? player.priestLevel : player.rangerLevel;
            int target = door.challengeLevel > championLevel ? 20 :
                         door.challengeLevel == championLevel ? 10 : 10 - 4 * (championLevel - door.challengeLevel);
            if (target < 1) target = 1;
            if (m_inTowerD20Value >= target) {
                m_inTowerFlowState = InTowerFlowState::FLOOR_CHALLENGE_SUCCESS;
                m_inTowerFlowStateStartTick = currentTick;
                m_inTowerDungeonPhase = 4;
                m_inTowerShrinkAnimStartTick = currentTick;
            } else {
                player.towerMissingChampion = false;
                door.state = DoorState::DOOR_CLOSED;
                grid.towerSectionOpen[m_inTowerOpenedRow] = false;
                player.towerResumeFloor = player.dungeonFloor;
                player.towerResumeDoor = m_inTowerOpenedCol;
                m_inTowerChallengeDoorOverrideActive = false;
                m_inTowerChallengeDoorOverrideRow = -1;
                m_inTowerChallengeDoorOverrideCol = -1;
                m_inTowerFlowState = InTowerFlowState::EXIT_TOWER;
                m_inTowerFlowStateStartTick = currentTick;
                m_inTowerDungeonPhase = 4;
                m_inTowerShrinkAnimStartTick = currentTick;
            }
        } else {
            m_inTowerResolutionStep = 1;
            m_inTowerResolutionStepStartTick = currentTick;
        }
    }

    if (m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT &&
        m_inTowerD20RollState == 2 && !m_inTowerResolutionApplied) {
        DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
        if (m_inTowerResolutionStep == 1 &&
            currentTick - m_inTowerResolutionStepStartTick >= kInTowerResolutionPointDelayMs) {
            if (m_inTowerEnemyRemaining > 0 && player.attackValue > 0) {
                --m_inTowerEnemyRemaining;
                --player.attackValue;
                m_inTowerEnemySlashType[m_inTowerEnemyRemaining] = (unsigned int)(rand() % 2);
                m_inTowerEnemyDeathTick[m_inTowerEnemyRemaining] = currentTick;
                m_swordFireAnimActive = true;
                m_swordFireAnimStartTick = currentTick;
                m_inTowerResolutionStepStartTick = currentTick;
            } else {
                m_inTowerPendingDamage = m_inTowerEnemyRemaining;
                m_inTowerResolutionStep = 2;
                m_inTowerResolutionStepStartTick = currentTick;
            }
        } else if (m_inTowerResolutionStep == 2 &&
                   currentTick - m_inTowerResolutionStepStartTick >= kInTowerResolutionPointDelayMs) {
            if (m_inTowerPendingDamage > 0 && player.defenseValue > 0) {
                --m_inTowerPendingDamage;
                --player.defenseValue;
                m_shieldShakeAnimActive = true;
                m_shieldShakeAnimStartTick = currentTick;
                m_shieldShakeLastChangeTick = currentTick;
                m_inTowerResolutionStepStartTick = currentTick;
            } else {
                m_inTowerResolutionStep = 3;
                m_inTowerResolutionStepStartTick = currentTick;
            }
         } else if (m_inTowerResolutionStep == 3 &&
                 currentTick - m_inTowerResolutionStepStartTick >= kInTowerResolutionPointDelayMs) {
            if (m_inTowerPendingDamage > 0) {
                --m_inTowerPendingDamage;
                --player.towerHitPoints;
                m_inTowerHitPointFlashTick = currentTick;
                m_inTowerResolutionStepStartTick = currentTick;
            } else {
                door.monsterCount = m_inTowerEnemyRemaining;
                m_inTowerResolutionStep = 4;
                m_inTowerResolutionStepStartTick = currentTick;
            }
         } else if (m_inTowerResolutionStep == 4 &&
                 currentTick - m_inTowerResolutionStepStartTick >= 600UL) {
            m_inTowerResolutionApplied = true;
            m_inTowerEnemiesActive = false;
            m_inTowerDungeonPhase = 4;
            m_inTowerShrinkAnimStartTick = currentTick;
            m_inTowerFlowStateStartTick = currentTick;

            if (player.towerHitPoints <= 0) {
                door.state = DoorState::DOOR_CLOSED;
                player.towerMissingChampion = false;
                player.towerResumeFloor = player.dungeonFloor;
                player.towerResumeDoor = m_inTowerOpenedCol;
                m_inTowerChallengeDoorOverrideActive = false;
                m_inTowerChallengeDoorOverrideRow = -1;
                m_inTowerChallengeDoorOverrideCol = -1;
                m_inTowerFlowState = InTowerFlowState::EXIT_TOWER;
            } else if (m_inTowerEnemyRemaining > 0) {
                m_inTowerD20RollState = 0;
                m_inTowerResolutionApplied = false;
                m_inTowerResolutionStep = 0;
                m_inTowerPendingDamage = 0;
                m_inTowerEnemiesActive = true;
                m_inTowerDungeonPhase = 2;
            } else if (door.role == TowerDoorRole::STAIRCASE) {
                grid.towerSectionOpen[m_inTowerOpenedRow] = true;
                m_inTowerFlowState = InTowerFlowState::FLOOR_CHALLENGE_VIDEO;
                m_inTowerChallengeDoorOverrideActive = true;
                m_inTowerChallengeDoorOverrideRow = m_inTowerOpenedRow;
                m_inTowerChallengeDoorOverrideCol = m_inTowerOpenedCol;
            } else if (door.role == TowerDoorRole::DRAGON) {
                m_inTowerFlowState = InTowerFlowState::DRAGON_VIDEO;
            } else {
                m_inTowerFlowState = InTowerFlowState::TOWER_CLIMB;
            }
        }
    }

    // Render the standard main screen base: black background, player scores,
    // status text and icons, NeoPixel animation
    if (!pbeRenderMainScreenBase(currentTick, lastTick)) {
        return (false);
    }

    if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_VIDEO ||
        m_inTowerFlowState == InTowerFlowState::DRAGON_VIDEO) {
        if (!m_inTowerVideoPlayer) m_inTowerVideoPlayer = new PBVideoPlayer(this, &m_soundSystem);
        if (!m_inTowerVideoLoaded) {
            const char* videoPath = "src/user/resources/videos/dragonmultiball.mp4";
            if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_VIDEO) {
                const DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
                videoPath = door.requiredChampion == TowerChampion::KNIGHT ? "src/user/resources/videos/knight.mp4" :
                            door.requiredChampion == TowerChampion::PRIEST ? "src/user/resources/videos/priest.mp4" :
                            "src/user/resources/videos/ranger.mp4";
            }
            m_inTowerVideoSpriteId = m_inTowerVideoPlayer->pbvpLoadVideo(videoPath, 0, 0, false);
            if (m_inTowerVideoSpriteId != NOSPRITE) {
                const stVideoInfo info = m_inTowerVideoPlayer->pbvpGetVideoInfo();
                const int videoX = ACTIVEDISPX + (1024 / 3) - info.width / 2;
                const int videoY = ACTIVEDISPY + 350 - info.height / 2;
                m_inTowerVideoPlayer->pbvpSetXY(videoX, videoY);
                m_inTowerVideoPlayer->pbvpSetVolume(0);
                m_inTowerVideoPlayer->pbvpPlay();
                m_inTowerVideoLoaded = true;
            } else {
                pbeSendConsole("ERROR: Failed to load InTower video");
                m_inTowerVideoSkipRequested = true;
            }
        }
        if (m_inTowerVideoLoaded) {
            m_inTowerVideoPlayer->pbvpUpdate(currentTick);
            m_inTowerVideoPlayer->pbvpRender();
            if (m_inTowerVideoSkipRequested || m_inTowerVideoPlayer->pbvpGetPlaybackState() == PBV_FINISHED) {
                m_inTowerVideoPlayer->pbvpStop();
                m_inTowerVideoPlayer->pbvpUnloadVideo();
                m_inTowerVideoSpriteId = NOSPRITE;
                m_inTowerVideoLoaded = false;
                m_inTowerVideoSkipRequested = true;
            }
        }
        return true;
    }

    // Render towerclimb image centered in the main score area
    int towerCenterX = ACTIVEDISPX + (1024 / 3);
    int towerCenterY = ACTIVEDISPY + 350;
    gfxRenderSprite(m_TowerClimbId, towerCenterX, towerCenterY);

    int towerHalfWidth  = (int)(gfxGetBaseWidth(m_TowerClimbId) / 2);
    int towerHalfHeight = (int)(gfxGetBaseHeight(m_TowerClimbId) / 2);
    int towerTopLeftX   = towerCenterX - towerHalfWidth;
    int towerTopLeftY   = towerCenterY - towerHalfHeight;

#ifdef D20_CALIBRATION
    // --- D20 CALIBRATION render override (developer tool) ----------------
    if (s_d20CalibActive && m_inTowerD20Loaded) {
        pbeUpdateInTowerD20(currentTick); // applies the current calib orientation
        pb3dSetInstancePositionPx(m_inTowerD20InstanceId, (float)towerCenterX, (float)towerCenterY - 40.0f, 0.0f);
        pb3dBegin();
        pb3dRenderInstance(m_inTowerD20InstanceId);
        pb3dEnd();

        float rx, ry, rz;
        d20CalibCurrentOrient(rx, ry, rz);

        // Render the D20 result, then the calibration detail below it, using the
        // same shadow-string renderer as the normal dice value (no snprintf).
        std::string angleText  = "rx " + std::to_string((int)lroundf(rx))
                               + "  ry " + std::to_string((int)lroundf(ry))
                               + "  rz " + std::to_string((int)lroundf(rz));
        std::string resultText;
        std::string faceText;
        std::string helpText;
        if (s_d20CalibPhase == 0) {
            resultText = "ORIENT: bottom edge horizontal";
            faceText   = "offset " + std::to_string((int)lroundf(d20RadToDeg(s_d20CalibAngleOffset))) + " deg";
            helpText   = "LFLIP/RFLIP=rotate  LACT/RACT=set  START=exit";
        } else {
            resultText = "D20: " + std::to_string(s_d20CalibValue);
            faceText   = "face " + std::to_string(s_d20CalibFaceIdx + 1) + "/" + std::to_string(s_d20CalibFaceCount)
                       + "  rot " + std::to_string(s_d20CalibCandIdx * 60) + " deg";
            helpText   = "LFLIP=face RFLIP=corner LACT/RACT=value(logs) START=exit";
        }

        // Render the calibration text at half the font's normal size (keep the
        // same vertical offsets so the lines do not overlap), then restore.
        float prevFontScale = gfxGetScaleFactor(m_StartMenuFontId);
        gfxSetScaleFactor(m_StartMenuFontId, prevFontScale * 0.5f, false);

        gfxRenderShadowString(m_StartMenuFontId, resultText, towerCenterX, towerCenterY + 80,  3, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, faceText,   towerCenterX, towerCenterY + 120, 2, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, angleText,  towerCenterX, towerCenterY + 145, 2, GFX_TEXTCENTER, 0, 0, 0, 255, 2);
        gfxRenderShadowString(m_StartMenuFontId, helpText,   towerCenterX, towerCenterY + 170, 1, GFX_TEXTCENTER, 0, 0, 0, 255, 2);

        gfxSetScaleFactor(m_StartMenuFontId, prevFontScale, false);

        gfxRenderSprite(m_PBTBLMainScreenBGId, ACTIVEDISPX, ACTIVEDISPY);
        pbeRenderStatusText(currentTick, lastTick);
        return (true);
    }
#endif

    static constexpr float kDungeonFullscreenScale  = 0.69f;   // 0.8625 * 0.80 (-20%)
    static constexpr float kDungeonSmallScale       = 0.3248f; // 0.406  * 0.80 (-20%)
    static constexpr float kDungeonTransitionDurMs  = 500.0f;  // shrink and grow duration

    // Anchor points: fullscreen centred on towerclimb (shifted up 50 px); small in right half
    int fullX  = towerCenterX;
    int fullY  = towerCenterY - 10;  // -30 + 40 - 20px
    int smallX = towerCenterX + towerHalfWidth / 2 + 30;
    int smallY = towerCenterY + 20;

    if (m_inTowerDungeonPhase == 0) {
        // ---- Phase 0: dungeon fills the intower area; dice hidden -------
        pbeRenderDungeonGrid(kDungeonFullscreenScale, fullX, fullY, true, currentTick, lastTick);
    }
    else if (m_inTowerDungeonPhase == 1) {
        // ---- Phase 1: shrink from fullscreen to small -------------------
        float elapsedMs = (currentTick >= m_inTowerShrinkAnimStartTick)
                          ? (float)(currentTick - m_inTowerShrinkAnimStartTick) : 0.0f;
        float t = elapsedMs / kDungeonTransitionDurMs;
        if (t >= 1.0f) {
            t = 1.0f;
            m_inTowerDungeonPhase = 2;  // Animation complete — show dice
        }
        // Smooth-step ease: t^2*(3-2t)
        float tEase       = t * t * (3.0f - 2.0f * t);
        float renderScale = kDungeonFullscreenScale + (kDungeonSmallScale - kDungeonFullscreenScale) * tEase;
        int   renderX     = fullX + (int)((smallX - fullX) * tEase);
        int   renderY     = fullY + (int)((smallY - fullY) * tEase);
        pbeRenderDungeonGrid(renderScale, renderX, renderY, false, currentTick, lastTick);
    }
    else if (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3) {
        // ---- Phase 2/3: dungeon at small position; dice visible ----------
        pbeRenderDungeonGrid(kDungeonSmallScale, smallX, smallY, false, currentTick, lastTick);

        if (m_inTowerD20Loaded) {
            pbeUpdateInTowerD20(currentTick);
            int diceX = towerTopLeftX + 220;
            int diceY = towerTopLeftY + 140 - 10;

            // While the die spins it hops around a small circle, then settles
            // back to the centre (its final resting spot) once it stops.
            float bounceX = 0.0f, bounceY = 0.0f;
            if (m_inTowerD20RollState == 1 || m_inTowerD20RollState == 2) {
                const float kBounceRadiusPx = 22.0f; // circle radius
                const float kBounceOmega    = 9.0f;  // rad/sec around the circle
                const float kBounceHopPx    = 10.0f; // extra vertical hop
                const float kSettleMs       = 350.0f;
                float spinSec = (currentTick >= m_inTowerD20SpinStartTick)
                              ? (float)(currentTick - m_inTowerD20SpinStartTick) / 1000.0f : 0.0f;
                float radius = kBounceRadiusPx;
                if (m_inTowerD20RollState == 2) {
                    // Ease the radius down to zero so it glides back to centre.
                    float s = (currentTick >= m_inTowerD20StopTick)
                            ? (float)(currentTick - m_inTowerD20StopTick) / kSettleMs : 0.0f;
                    if (s > 1.0f) s = 1.0f;
                    float ease = 1.0f - (1.0f - s) * (1.0f - s); // ease-out
                    radius = kBounceRadiusPx * (1.0f - ease);
                }
                float theta = spinSec * kBounceOmega;
                float scale = radius / kBounceRadiusPx;
                bounceX = radius * cosf(theta);
                bounceY = radius * sinf(theta) - fabsf(sinf(theta * 2.0f)) * kBounceHopPx * scale;
            }
            pb3dSetInstancePositionPx(m_inTowerD20InstanceId, (float)diceX + bounceX, (float)diceY + bounceY, 0.0f);
            pb3dBegin();
            pb3dRenderInstance(m_inTowerD20InstanceId);
            pb3dEnd();
            // m_inTowerD20Value holds the rolled value for later use (not shown).
        }

        // ---- Warrior enemies: spawn, animate and draw under the dice -----
        if (m_inTowerEnemiesActive && m_inTowerEnemyLoaded && m_inTowerEnemyCount > 0) {
            // Region: below the dice and to the left of the minimized dungeon map,
            // inset 50px on all sides so the enemies cluster more tightly together
            int diceX = towerTopLeftX + 220;
            int diceY = towerTopLeftY + 140;
            int xMin  = towerTopLeftX + 30 + 50 - 25;
            int xMax  = smallX - 80 - 50 - 20 - 30 + 20;
            int yMax  = towerTopLeftY + 2 * towerHalfHeight - 40 - 50 - 20 - 20 + 20;
            if (xMax <= xMin) xMax = xMin + 1;

            const float colStep = (float)(xMax - xMin) / 4.0f; // 5 columns span the width
            const int   rowStep = 80;                          // vertical gap between ranks

            // Map a center-out fill cell (kEnemyFillOrder) to a screen position.
            auto cellXY = [&](const EnemyCell& cell, int& outX, int& outY) {
                bool  wide   = (cell.row % 2 == 1);                 // rows 1,3,5 = 5 wide
                float startX = wide ? (float)xMin : (float)xMin + colStep * 0.5f;
                outX = (int)(startX + (cell.pos - 1) * colStep);
                outY = yMax - (cell.row - 1) * rowStep;             // row 1 at bottom
            };

            // One-shot spawn: place each enemy at its center-out cell.
            if (m_inTowerEnemiesNeedSpawn) {
                for (int i = 0; i < m_inTowerEnemyCount && i < 20; i++) {
                    unsigned int inst = m_inTowerEnemyInstanceIds[i];
                    if (inst == NOSPRITE) continue;
                    int ex, ey;
                    cellXY(kEnemyFillOrder[i], ex, ey);
                    unsigned int base = (rand() % 2) ? 3u : 0u; // pick walk range 0-2 or 3-4
                    gfxSetSelectedTile(inst, base);                // start at the bottom of the range
                    gfxSetColor(inst, 255, 255, 255, 255);         // fully opaque (clear any prior fade)
                    gfxSetXY(inst, ex, ey, false);
                }
                m_inTowerEnemiesNeedSpawn = false;
                m_inTowerEnemyAnimTick    = currentTick;
            }

            // Every 250ms, each surviving enemy has a 25% chance to advance within its range
            if (currentTick - m_inTowerEnemyAnimTick >= 250) {
                for (int i = 0; i < m_inTowerEnemyCount && i < m_inTowerEnemyRemaining; i++) {
                    unsigned int inst = m_inTowerEnemyInstanceIds[i];
                    if (inst == NOSPRITE) continue;
                    if (rand() % 4 == 0) {
                        unsigned int cur  = gfxGetSelectedTile(inst);
                        unsigned int next = (cur < 3) ? ((cur + 1) % 3)
                                                      : (3 + ((cur - 3 + 1) % 2));
                        gfxSetSelectedTile(inst, next);
                    }
                }
                m_inTowerEnemyAnimTick = currentTick;
            }

            // Draw top-to-bottom (rows 5..1) so the nearer/front ranks overlay the
            // ones behind and their heads stay visible.  Eliminated enemies (index
            // >= remaining) render statically as a corpse (tile 5) and fade out
            // over 0.5s from the moment the die stopped.
            for (int r = 5; r >= 1; r--) {
                for (int i = 0; i < m_inTowerEnemyCount && i < 20; i++) {
                    if (kEnemyFillOrder[i].row == r && m_inTowerEnemyInstanceIds[i] != NOSPRITE) {
                        bool         dying = (i >= m_inTowerEnemyRemaining);
                        unsigned int a     = 255;
                        if (dying) {
                            gfxSetSelectedTile(m_inTowerEnemyInstanceIds[i], 5);
                            float fade = 1.0f;
                            if (m_inTowerEnemyDeathTick[i] != 0 && currentTick >= m_inTowerEnemyDeathTick[i]) {
                                fade = 1.0f - (float)(currentTick - m_inTowerEnemyDeathTick[i]) / 1000.0f;
                                if (fade < 0.0f) fade = 0.0f;
                            }
                            // PNG sprites modulate alpha via the vertex colour, not
                            // textureAlpha, so fade through gfxSetColor.
                            a = (unsigned int)(fade * 255.0f);
                            gfxSetColor(m_inTowerEnemyInstanceIds[i], 255, 255, 255, a);
                        }
                        gfxRenderSprite(m_inTowerEnemyInstanceIds[i]);

                        // Slash overlay on dying enemies: draw the per-enemy slash
                        // variant (slash1/slash2) over the corpse, fading at the
                        // same rate.  Reuses the main-table base sprite IDs.
                        if (dying) {
                            unsigned int slashId = (m_inTowerEnemySlashType[i] == 0)
                                                   ? m_PBTBLSlash1Id : m_PBTBLSlash2Id;
                            if (slashId != NOSPRITE) {
                                static constexpr float kSlashScale = 0.55f; // ~half the enemy size
                                int ex, ey;
                                cellXY(kEnemyFillOrder[i], ex, ey);
                                // Enemy anchor is GFX_CENTER; slash anchor is
                                // GFX_UPPERLEFT, so offset by half the scaled 128px
                                // texture to centre it over the enemy.
                                int half = (int)(128.0f * kSlashScale * 0.5f);
                                gfxSetScaleFactor(slashId, kSlashScale, false);
                                gfxSetColor(slashId, 255, 255, 255, a);
                                gfxRenderSprite(slashId, ex - half, ey - half);
                                // Restore the load-time scale so Main mode's shield
                                // slash (same base sprite) renders unaffected.
                                gfxSetScaleFactor(slashId, 0.6f, false);
                            }
                        }
                    }
                }
            }
        }
    }
    else {
        // ---- Phase 4: grow from small back to fullscreen; dice hidden ----
        float elapsedMs = (currentTick >= m_inTowerShrinkAnimStartTick)
                          ? (float)(currentTick - m_inTowerShrinkAnimStartTick) : 0.0f;
        float t = elapsedMs / kDungeonTransitionDurMs;
        if (t >= 1.0f) {
            t = 1.0f;
            m_inTowerDungeonPhase = 0;  // Animation complete — back to fullscreen
        }
        // Smooth-step ease: t^2*(3-2t)
        float tEase       = t * t * (3.0f - 2.0f * t);
        float renderScale = kDungeonSmallScale + (kDungeonFullscreenScale - kDungeonSmallScale) * tEase;
        int   renderX     = smallX + (int)((fullX - smallX) * tEase);
        int   renderY     = smallY + (int)((fullY - smallY) * tEase);
        pbeRenderDungeonGrid(renderScale, renderX, renderY, false, currentTick, lastTick);
    }

    if (m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT &&
        (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3)) {
        const DoorCell& door = grid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol];
        const char* champion = door.requiredChampion == TowerChampion::KNIGHT ? "Knight" :
                               door.requiredChampion == TowerChampion::PRIEST ? "Priest" : "Ranger";
        const int championLevel = door.requiredChampion == TowerChampion::KNIGHT ? player.knightLevel :
                                  door.requiredChampion == TowerChampion::PRIEST ? player.priestLevel : player.rangerLevel;
        int target = door.challengeLevel > championLevel ? 20 :
                     door.challengeLevel == championLevel ? 10 : 10 - 4 * (championLevel - door.challengeLevel);
        if (target < 1) target = 1;
        gfxSetColor(m_StartMenuFontId, 255, 215, 0, 255);
        gfxRenderString(m_StartMenuFontId, std::string(champion) + " Level " + std::to_string(door.challengeLevel),
                        towerTopLeftX + 220, towerTopLeftY + 370, 4, GFX_TEXTCENTER);
        gfxSetColor(m_StartMenuFontId, 255, 255, 255, 255);
        gfxRenderString(m_StartMenuFontId, "Roll " + std::to_string(target) + " or higher",
                        towerTopLeftX + 220, towerTopLeftY + 420, 3, GFX_TEXTCENTER);
    }

    if (m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT &&
        (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3)) {
        const bool flashHitPoints = m_inTowerHitPointFlashTick != 0 &&
                                   currentTick - m_inTowerHitPointFlashTick < kInTowerHitPointFlashMs;
        gfxSetColor(m_StartMenuFontId, 255, flashHitPoints ? 70 : 255, flashHitPoints ? 70 : 255, 255);
        gfxRenderString(m_StartMenuFontId, "HP: " + std::to_string(player.towerHitPoints),
                        smallX, smallY - 165, 6, GFX_TEXTCENTER);
    }

    if (m_inTowerFlowState == InTowerFlowState::EXIT_TOWER) {
        const std::string result = player.towerMissingChampion ? "Missing Champion" : "Defeated!";
        const std::string detail = player.towerMissingChampion ? "" : "Try Again";
        gfxSetColor(m_StartMenuFontId, 255, 215, 0, 255);
        gfxRenderString(m_StartMenuFontId, result, towerCenterX, towerCenterY - 80, 6, GFX_TEXTCENTER);
        gfxSetColor(m_StartMenuFontId, 255, 255, 255, 255);
        if (!detail.empty()) gfxRenderString(m_StartMenuFontId, detail, towerCenterX, towerCenterY - 25, 4, GFX_TEXTCENTER);
        if (m_inTowerAvatarId != NOSPRITE) {
            gfxRenderSprite(m_inTowerAvatarId, towerCenterX, towerCenterY + 80, 1.5f, 0.0f);
        }
    }

    // Render divider bars on top, same as pbeRenderMainScreen
    gfxRenderSprite(m_PBTBLMainScreenBGId, ACTIVEDISPX, ACTIVEDISPY);

    // Re-render ball text and status text above the tower image and overlay
    pbeRenderStatusText(currentTick, lastTick);

    return (true);
}

// ========================================================================
// PBTBL_INTOWER: State Update Function
// ========================================================================

void PBEngine::pbeUpdateStateInTower(stInputMessage inputMessage) {

    if (inputMessage.inputMsg == PB_IMSG_BUTTON && inputMessage.inputState == PB_ON) {

#ifdef D20_CALIBRATION
        // ------------------------------------------------------------
        // D20 CALIBRATION input handling (developer tool).  IDI_START
        // toggles the mode; while active, all input drives calibration and
        // normal InTower handling is bypassed.  Safe to remove this block.
        // ------------------------------------------------------------
        if (inputMessage.inputId == IDI_START) {
            s_d20CalibActive = !s_d20CalibActive;
            if (s_d20CalibActive) {
                if (!d20CalibParseModel()) {
                    pbeSendConsole("D20 CALIB: failed to parse d20dice.glb");
                    s_d20CalibActive = false;
                } else {
                    s_d20CalibPhase       = 0;   // start in the orientation phase
                    s_d20CalibAngleOffset = d20DegToRad(-90.0f);
                    s_d20CalibFaceIdx     = 0;
                    s_d20CalibCandIdx     = 0;
                    s_d20CalibValue       = 1;
                    pbeSendConsole("D20 CALIB: enabled - orient bottom edge horizontal (LFLIP/RFLIP), LACT/RACT to set");
                }
            } else {
                pb3dSetInstanceRotation(m_inTowerD20InstanceId, m_inTowerD20RotX, m_inTowerD20RotY, m_inTowerD20RotZ);
                pbeSendConsole("D20 CALIB: disabled");
            }
            return;
        }
        if (s_d20CalibActive) {
            if (s_d20CalibPhase == 0) {
                // --- Phase 0: dial the in-plane rotation until the bottom edge
                // is horizontal.  Flippers nudge +/- 0.5 deg; activate locks it. ---
                const float kStep = d20DegToRad(0.5f);
                if (inputMessage.inputId == IDI_LFLIP) {
                    s_d20CalibAngleOffset -= kStep;
                } else if (inputMessage.inputId == IDI_RFLIP) {
                    s_d20CalibAngleOffset += kStep;
                } else if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                    s_d20CalibPhase = 1; // lock orientation, move on to number calibration
                    pbeSendConsole("D20 CALIB: orientation set - now stepping numbers (LACT/RACT logs each)");
                }
                return;
            }
            // --- Phase 1: number calibration (uses the locked orientation) ---
            if (inputMessage.inputId == IDI_LFLIP) {
                if (s_d20CalibFaceCount > 0) s_d20CalibFaceIdx = (s_d20CalibFaceIdx + 1) % s_d20CalibFaceCount;
                s_d20CalibCandIdx = 0;
            } else if (inputMessage.inputId == IDI_RFLIP) {
                s_d20CalibCandIdx = (s_d20CalibCandIdx + 1) % 6; // 60 deg steps
            } else if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                // Moving the value logs the tuple for the value currently shown
                // (the "previous" value) before advancing to the next one.
                float rx, ry, rz;
                d20CalibCurrentOrient(rx, ry, rz);
                std::string tuple = "{ " + std::to_string(rx) + "f, " + std::to_string(ry) + "f, "
                                  + std::to_string(rz) + "f }, // value " + std::to_string(s_d20CalibValue);
                pbeSendConsole(tuple);

                if (inputMessage.inputId == IDI_LACTIVATE) {
                    s_d20CalibValue = (s_d20CalibValue <= 1) ? 20 : s_d20CalibValue - 1;
                } else {
                    s_d20CalibValue = (s_d20CalibValue >= 20) ? 1 : s_d20CalibValue + 1;
                }
            }
            return;
        }
#endif // D20_CALIBRATION

        const unsigned long currentTick = GetTickCountGfx();
        pbGameState& player = m_playerStates[m_currentPlayer];
        TowerDungeonGrid& grid = player.dungeonGrid;

        if (m_inTowerFlowState == InTowerFlowState::TOWER_CLIMB) {
            const int row = player.dungeonFloor - 1;
            if (row >= 0 && row < 5) {
                const auto isClosedDoor = [&](int column) {
                    return grid.cells[row][column].state == DoorState::DOOR_CLOSED;
                };
                if (inputMessage.inputId == IDI_LFLIP || inputMessage.inputId == IDI_RFLIP) {
                    const int step = inputMessage.inputId == IDI_LFLIP ? -1 : 1;
                    int column = m_inTowerSelectedDoor;
                    if (column < 0 || column >= 3 ||
                        !isClosedDoor(column)) {
                        column = -1;
                        const int firstColumn = step < 0 ? 2 : 0;
                        const int lastColumn = step < 0 ? -1 : 3;
                        for (int candidate = firstColumn; candidate != lastColumn; candidate += step) {
                            if (isClosedDoor(candidate)) {
                                column = candidate;
                                break;
                            }
                        }
                        m_inTowerSelectedDoor = column;
                    }

                    for (int candidate = column + step; candidate >= 0 && candidate < 3; candidate += step) {
                        if (isClosedDoor(candidate)) {
                            m_inTowerSelectedDoor = candidate;
                            break;
                        }
                    }
                } else if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                    const int column = m_inTowerSelectedDoor;
                    if (column >= 0 && column < 3 && grid.cells[row][column].state == DoorState::DOOR_CLOSED) {
                        DoorCell& door = grid.cells[row][column];
                        door.state = DoorState::DOOR_OPEN;
                        if (door.hasLadder || door.role == TowerDoorRole::STAIRCASE) {
                            grid.towerSectionOpen[row] = false;
                            m_inTowerChallengeDoorOverrideActive = true;
                            m_inTowerChallengeDoorOverrideRow = row;
                            m_inTowerChallengeDoorOverrideCol = column;
                        }
                        m_inTowerOpenedRow = row;
                        m_inTowerOpenedCol = column;
                        m_inTowerDoorJustOpened = true;
                        m_inTowerAvatarOpenTick = currentTick;
                        m_inTowerAvatarRoomProgress = 0.0f;
                        m_inTowerFlowStateStartTick = currentTick;
                    }
                }
            }
            pbeUpdateModeSystem(inputMessage, currentTick);
            return;
        }

        if (m_inTowerFlowState == InTowerFlowState::ROOM_FIGHT ||
            m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_FIGHT) {
            if (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) {
                if (!m_inTowerD20Loaded) {
                    m_inTowerD20Value = (rand() % 20) + 1;
                    m_inTowerD20RollState = 2;
                    m_inTowerD20StopTick = currentTick;
                } else if (m_inTowerD20RollState == 0) {
                    m_inTowerD20Value = (rand() % 20) + 1;
                    m_inTowerRollEnemyCount = m_inTowerEnemyRemaining;
                    m_inTowerD20RollState = 1;
                    m_inTowerD20SpinStartTick = currentTick;
                    m_inTowerD20SpinBaseRotX = m_inTowerD20RotX;
                    m_inTowerD20SpinBaseRotY = m_inTowerD20RotY;
                    m_inTowerD20SpinBaseRotZ = m_inTowerD20RotZ;
                } else if (m_inTowerD20RollState == 1) {
                    const D20Orient& orientation = kD20Orient[(m_inTowerD20Value - 1) % 20];
                    m_inTowerD20RotX = orientation.rx;
                    m_inTowerD20RotY = orientation.ry + kD20YawTrimDeg;
                    m_inTowerD20RotZ = orientation.rz;
                    m_inTowerD20RollState = 2;
                    m_inTowerD20StopTick = currentTick;
                    m_inTowerEnemyRemaining = m_inTowerRollEnemyCount - m_inTowerD20Value;
                    if (m_inTowerEnemyRemaining < 0) m_inTowerEnemyRemaining = 0;
                    for (int i = m_inTowerEnemyRemaining; i < m_inTowerRollEnemyCount && i < 20; ++i) {
                        m_inTowerEnemySlashType[i] = (unsigned int)(rand() % 2);
                        m_inTowerEnemyDeathTick[i] = currentTick;
                    }
                }
            }
            pbeUpdateModeSystem(inputMessage, currentTick);
            return;
        }

           if ((m_inTowerFlowState == InTowerFlowState::FLOOR_CHALLENGE_VIDEO ||
               m_inTowerFlowState == InTowerFlowState::DRAGON_VIDEO) &&
            (inputMessage.inputId == IDI_LACTIVATE || inputMessage.inputId == IDI_RACTIVATE) &&
            currentTick - m_inTowerFlowStateStartTick >= 750UL) {
            m_inTowerVideoSkipRequested = true;
        }

        pbeUpdateModeSystem(inputMessage, currentTick);
        return;

        // ------------------------------------------------------------
        // Flippers: behaviour depends on current dungeon phase
        // ------------------------------------------------------------
        if (inputMessage.inputId == IDI_LFLIP || inputMessage.inputId == IDI_RFLIP) {

            if (m_inTowerDungeonPhase == 0) {
                if (!m_inTowerDoorJustOpened) {
                    // First press: open the next available door; stay fullscreen
                    TowerDungeonGrid& grid = m_playerStates[m_currentPlayer].dungeonGrid;
                    for (int r = 0; r < 5; r++) {
                        for (int c = 0; c < 3; c++) {
                            if (grid.cells[r][c].state != DoorState::DOOR_NONE &&
                                grid.cells[r][c].state != DoorState::DOOR_OPEN) {
                                grid.cells[r][c].state = DoorState::DOOR_OPEN;
                                // If this door has stairs, open the corresponding
                                // side-tower TC section (TC[r] sits between floor r and r+1)
                                if (grid.cells[r][c].hasLadder && r < 5) {
                                    grid.towerSectionOpen[r] = true;
                                }
                                m_inTowerDoorJustOpened = true;
                                m_inTowerOpenedRow = r;
                                m_inTowerOpenedCol = c;
                                m_inTowerAvatarOpenTick = GetTickCountGfx();
                                goto doorOpenDone;
                            }
                        }
                    }
                    doorOpenDone:;
                } else {
                    // Second press: start shrink animation; spawn this room's enemies
                    m_inTowerDoorJustOpened = false;
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase = 1;

                    int enemies = 0;
                    if (m_inTowerOpenedRow >= 0 && m_inTowerOpenedCol >= 0) {
                        enemies = m_playerStates[m_currentPlayer]
                                      .dungeonGrid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol].monsterCount;
                    }
                    if (enemies < 0)  enemies = 0;
                    if (enemies > 20) enemies = 20;
                    m_inTowerEnemyCount       = enemies;
                    m_inTowerEnemyRemaining   = enemies;
                    m_inTowerEnemiesNeedSpawn = (enemies > 0);
                    m_inTowerEnemiesActive    = (enemies > 0);
                }
            }
            else if (m_inTowerDungeonPhase == 2 || m_inTowerDungeonPhase == 3) {
                // Dice screen: flippers drive the roll state machine.
                //   state 0 (READY)    -> pick value now, start fast spin
                //   state 1 (SPINNING) -> stop spin, snap rolled value flat/upright
                //   state 2 (STOPPED)  -> grow dungeon back to fullscreen
                if (!m_inTowerD20Loaded) {
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase = 4;
                    m_inTowerEnemiesActive    = false;
                    m_inTowerEnemiesNeedSpawn = false;
                }
                else if (m_inTowerD20RollState == 0) {
                    m_inTowerD20Value         = (rand() % 20) + 1;
                    m_inTowerD20RollState     = 1;
                    m_inTowerD20SpinStartTick = GetTickCountGfx();
                    m_inTowerD20SpinBaseRotX  = m_inTowerD20RotX;
                    m_inTowerD20SpinBaseRotY  = m_inTowerD20RotY;
                    m_inTowerD20SpinBaseRotZ  = m_inTowerD20RotZ;
                    m_inTowerDungeonPhase     = 2;
                }
                else if (m_inTowerD20RollState == 1) {
                    // Global yaw trim: nudge every face slightly about Y so
                    // the displayed face reads perfectly flat.
                    const D20Orient& o = kD20Orient[(m_inTowerD20Value - 1) % 20];
                    m_inTowerD20RotX      = o.rx;
                    m_inTowerD20RotY      = o.ry + kD20YawTrimDeg;
                    m_inTowerD20RotZ      = o.rz;
                    m_inTowerD20RollState = 2;
                    m_inTowerD20StopTick  = GetTickCountGfx(); // begin bounce settle
                    // Resolve eliminations: the rolled value destroys that many
                    // enemies (outermost first); survivors keep animating.
                    int remaining = m_inTowerEnemyCount - m_inTowerD20Value;
                    if (remaining < 0) remaining = 0;
                    m_inTowerEnemyRemaining = remaining;
                    // Pick a slash overlay variant (slash1/slash2) for each enemy
                    // marked for death, fixed now so it doesn't flicker during fade.
                    for (int i = remaining; i < m_inTowerEnemyCount && i < 20; i++) {
                        m_inTowerEnemySlashType[i] = (unsigned int)(rand() % 2);
                    }
                }
                else {
                    m_inTowerD20RollState        = 0;
                    m_inTowerShrinkAnimStartTick = GetTickCountGfx();
                    m_inTowerDungeonPhase        = 4;
                    m_inTowerEnemiesActive    = false;
                    m_inTowerEnemiesNeedSpawn = false;
                    // Persist the reduction: destroyed enemies stay dead, so the
                    // opened room now only contains the survivors next visit.
                    m_inTowerEnemyCount = m_inTowerEnemyRemaining;
                    if (m_inTowerOpenedRow >= 0 && m_inTowerOpenedCol >= 0) {
                        m_playerStates[m_currentPlayer]
                            .dungeonGrid.cells[m_inTowerOpenedRow][m_inTowerOpenedCol]
                            .monsterCount = m_inTowerEnemyRemaining;
                    }
                }
            }
            // Phase 1/4 (animating): ignore flipper presses
        }

        // ------------------------------------------------------------
        // Activate buttons: change test dungeon level and re-initialise
        // Left activate  → level - 1 (min 1)
        // Right activate → level + 1 (max 3)
        // ------------------------------------------------------------
        else if (inputMessage.inputId == IDI_LACTIVATE) {
            if (s_testDungeonLevel > 1) {
                s_testDungeonLevel--;
                pbeInitDungeonGrid(m_currentPlayer, s_testDungeonLevel);
            }
        }
        else if (inputMessage.inputId == IDI_RACTIVATE) {
            if (s_testDungeonLevel < 3) {
                s_testDungeonLevel++;
                pbeInitDungeonGrid(m_currentPlayer, s_testDungeonLevel);
            }
        }
    }

    // Always run mode-system bookkeeping
    pbeUpdateModeSystem(inputMessage, GetTickCountGfx());
}
